(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about"],{

/***/ "./src/components/AboutComponent.svelte":
/*!**********************************************!*\
  !*** ./src/components/AboutComponent.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/AboutComponent.svelte generated by Svelte v3.24.0 */


const file = "src/components/AboutComponent.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-dych8n-style";
	style.textContent = ".btn-danger.svelte-dych8n.svelte-dych8n{margin-bottom:10px}a.svelte-dych8n.svelte-dych8n{text-decoration:inherit;color:inherit;cursor:pointer}.bounce.svelte-dych8n.svelte-dych8n{animation:svelte-dych8n-bounce 2s infinite}@keyframes svelte-dych8n-bounce{0%,20%,50%,80%,100%{transform:translateY(0)}40%{transform:translateY(-30px)}60%{transform:translateY(-15px)}}.fa-angle-double-down.svelte-dych8n.svelte-dych8n{font-size:70px !important}@media(min-width: 768px){.jumbotron.svelte-dych8n.svelte-dych8n{background-image:url(\"assets/Images/about/espacio.jpg\");background-size:cover;background-repeat:no-repeat;color:white;height:90vh;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.arrow.svelte-dych8n.svelte-dych8n{text-align:center;margin:8% 0;position:absolute;top:80vh;left:48vw;color:white;padding:0;margin:0;z-index:4;display:inline;text-align:center;opacity:0.6}.title.svelte-dych8n h1.svelte-dych8n{padding-top:29vh;font-size:5.5rem}.lead.svelte-dych8n.svelte-dych8n{font-size:1.7vw;padding-bottom:20px;padding-top:30vh}.aleimg.svelte-dych8n.svelte-dych8n{max-width:12vw;padding-left:20px}}.nosotras-title.svelte-dych8n.svelte-dych8n{padding:15px;color:rgb(190, 86, 89) !important}@media(max-width: 768px){.jumbotron.svelte-dych8n.svelte-dych8n{background-image:url(\"assets/Images/about/espacio.jpg\");background-size:cover;background-repeat:no-repeat;color:white;height:180vw;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.title.svelte-dych8n h1.svelte-dych8n{padding-top:0;font-size:60px !important}.lead.svelte-dych8n.svelte-dych8n{font-size:18px;padding-bottom:20px;margin-bottom:25px}.aleimg.svelte-dych8n.svelte-dych8n{max-width:100px;padding-left:20px}}.fas.svelte-dych8n.svelte-dych8n{font-size:70px;color:white !important}.align-text-bottom.svelte-dych8n.svelte-dych8n{vertical-align:text-bottom !important}.media.svelte-dych8n.svelte-dych8n{display:-ms-flexbox;padding:5px;display:flex;-ms-flex-align:start;align-items:flex-start}.nosotras.svelte-dych8n.svelte-dych8n{padding:15px;color:rgb(190, 86, 89) !important}.espacio.svelte-dych8n.svelte-dych8n{color:rgb(190, 86, 89) !important;padding-bottom:15px}.visita.svelte-dych8n.svelte-dych8n{opacity:0.5;padding-bottom:3px}.map.svelte-dych8n.svelte-dych8n{width:100vw;height:40vh}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWJvdXRDb21wb25lbnQuc3ZlbHRlIiwic291cmNlcyI6WyJBYm91dENvbXBvbmVudC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGFsZSA9IFwiYXNzZXRzL0ltYWdlcy9hYm91dC9hbGUucG5nXCI7XG4gIGxldCBlc3RlZmkgPSBcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXN0ZWZpLnBuZ1wiO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLmJ0bi1kYW5nZXIge1xuICAgIG1hcmdpbi1ib3R0b206IDEwcHg7XG4gIH1cbiAgYSB7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBpbmhlcml0O1xuICAgIGNvbG9yOiBpbmhlcml0O1xuICAgIGN1cnNvcjogcG9pbnRlcjtcbiAgfVxuICAuYm91bmNlIHtcbiAgICBhbmltYXRpb246IGJvdW5jZSAycyBpbmZpbml0ZTtcbiAgfVxuXG4gIEBrZXlmcmFtZXMgYm91bmNlIHtcbiAgICAwJSxcbiAgICAyMCUsXG4gICAgNTAlLFxuICAgIDgwJSxcbiAgICAxMDAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgwKTtcbiAgICB9XG4gICAgNDAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMzBweCk7XG4gICAgfVxuICAgIDYwJSB7XG4gICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTE1cHgpO1xuICAgIH1cbiAgfVxuXG4gIC5mYS1hbmdsZS1kb3VibGUtZG93biB7XG4gICAgZm9udC1zaXplOiA3MHB4ICFpbXBvcnRhbnQ7XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgLmp1bWJvdHJvbiB7XG4gICAgICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoXCJhc3NldHMvSW1hZ2VzL2Fib3V0L2VzcGFjaW8uanBnXCIpO1xuICAgICAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgICAgIGJhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7XG4gICAgICBjb2xvcjogd2hpdGU7XG4gICAgICBoZWlnaHQ6IDkwdmg7XG4gICAgICBtYXJnaW46IDAgIWltcG9ydGFudDtcbiAgICAgIG92ZXJmbG93OiBoaWRkZW47XG4gICAgICBwYWRkaW5nLXRvcDogMTVweCAhaW1wb3J0YW50O1xuICAgICAgcGFkZGluZy1ib3R0b206IDAgIWltcG9ydGFudDtcbiAgICAgIGJvcmRlci1yYWRpdXM6IDAgIWltcG9ydGFudDtcbiAgICB9XG4gICAgLmFycm93IHtcbiAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICAgIG1hcmdpbjogOCUgMDtcbiAgICAgIHBvc2l0aW9uOiBhYnNvbHV0ZTtcbiAgICAgIHRvcDogODB2aDtcbiAgICAgIGxlZnQ6IDQ4dnc7XG4gICAgICBjb2xvcjogd2hpdGU7XG4gICAgICBwYWRkaW5nOiAwO1xuICAgICAgbWFyZ2luOiAwO1xuICAgICAgei1pbmRleDogNDtcbiAgICAgIGRpc3BsYXk6IGlubGluZTtcbiAgICAgIHRleHQtYWxpZ246IGNlbnRlcjtcbiAgICAgIG9wYWNpdHk6IDAuNjtcbiAgICB9XG5cbiAgICAudGl0bGUgaDEge1xuICAgICAgcGFkZGluZy10b3A6IDI5dmg7XG4gICAgICBmb250LXNpemU6IDUuNXJlbTtcbiAgICB9XG4gICAgLmxlYWQge1xuICAgICAgZm9udC1zaXplOiAxLjd2dztcbiAgICAgIHBhZGRpbmctYm90dG9tOiAyMHB4O1xuICAgICAgcGFkZGluZy10b3A6IDMwdmg7XG4gICAgfVxuXG4gICAgLmFsZWltZyB7XG4gICAgICBtYXgtd2lkdGg6IDEydnc7XG4gICAgICBwYWRkaW5nLWxlZnQ6IDIwcHg7XG4gICAgfVxuICB9XG5cbiAgLm5vc290cmFzLXRpdGxlIHtcbiAgICBwYWRkaW5nOiAxNXB4O1xuICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gIH1cblxuICBAbWVkaWEgKG1heC13aWR0aDogNzY4cHgpIHtcbiAgICAuanVtYm90cm9uIHtcbiAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybChcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXNwYWNpby5qcGdcIik7XG4gICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIGhlaWdodDogMTgwdnc7XG4gICAgICBtYXJnaW46IDAgIWltcG9ydGFudDtcbiAgICAgIG92ZXJmbG93OiBoaWRkZW47XG4gICAgICBwYWRkaW5nLXRvcDogMTVweCAhaW1wb3J0YW50O1xuICAgICAgcGFkZGluZy1ib3R0b206IDAgIWltcG9ydGFudDtcbiAgICAgIGJvcmRlci1yYWRpdXM6IDAgIWltcG9ydGFudDtcbiAgICB9XG5cbiAgICAudGl0bGUgaDEge1xuICAgICAgcGFkZGluZy10b3A6IDA7XG4gICAgICBmb250LXNpemU6IDYwcHggIWltcG9ydGFudDtcbiAgICB9XG4gICAgLmxlYWQge1xuICAgICAgZm9udC1zaXplOiAxOHB4O1xuICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICAvKiBwYWRkaW5nLXRvcDogOyAqL1xuICAgICAgbWFyZ2luLWJvdHRvbTogMjVweDtcbiAgICB9XG5cbiAgICAuYWxlaW1nIHtcbiAgICAgIG1heC13aWR0aDogMTAwcHg7XG4gICAgICBwYWRkaW5nLWxlZnQ6IDIwcHg7XG4gICAgfVxuICB9XG5cbiAgLmZhcyB7XG4gICAgZm9udC1zaXplOiA3MHB4O1xuICAgIGNvbG9yOiB3aGl0ZSAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmFsaWduLXRleHQtYm90dG9tIHtcbiAgICB2ZXJ0aWNhbC1hbGlnbjogdGV4dC1ib3R0b20gIWltcG9ydGFudDtcbiAgfVxuXG4gIC5tZWRpYSB7XG4gICAgZGlzcGxheTogLW1zLWZsZXhib3g7XG4gICAgcGFkZGluZzogNXB4O1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgLW1zLWZsZXgtYWxpZ246IHN0YXJ0O1xuICAgIGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0O1xuICB9XG4gIC5ub3NvdHJhcyB7XG4gICAgcGFkZGluZzogMTVweDtcbiAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmVzcGFjaW8ge1xuICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gICAgcGFkZGluZy1ib3R0b206IDE1cHg7XG4gIH1cbiAgLnZpc2l0YSB7XG4gICAgb3BhY2l0eTogMC41O1xuICAgIHBhZGRpbmctYm90dG9tOiAzcHg7XG4gIH1cblxuICAubWFwIHtcbiAgICB3aWR0aDogMTAwdnc7XG4gICAgaGVpZ2h0OiA0MHZoO1xuICB9XG48L3N0eWxlPlxuXG48ZGl2IGNsYXNzPVwiZnVsbGNvbnRhaW5lclwiPlxuICA8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XG4gICAgPGRpdiBjbGFzcz1cImJhbm5lclwiPlxuICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC02IHRpdGxlIHB0LXhzLTEwXCI+XG4gICAgICAgICAgPGgxIGNsYXNzPVwiIHRleHQtY2VudGVyXCI+XG4gICAgICAgICAgICDCv1F1w6kgZXNcbiAgICAgICAgICAgIDxiciAvPlxuICAgICAgICAgICAgWmFyaWfDvGV5YT9cbiAgICAgICAgICA8L2gxPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNlwiPlxuICAgICAgICAgIDxwIGNsYXNzPVwibGVhZCB0ZXh0LWNlbnRlciBkZXNjXCI+XG4gICAgICAgICAgICBVbiBlc3BhY2lvIGRlc3RpbmFkbyBhIGxhcyBmYW1pbGlhcyBkb25kZSBwb2Ryw6FuIGFzZXNvcmFyc2UgZW5cbiAgICAgICAgICAgIHBvcnRlbyBlcmdvbm9taWNvLCBjb25vY2VyIGRpZmVyZW50ZXMgbW9kZWxvcyBkZSBwb3J0YWJlYsOpcyB5XG4gICAgICAgICAgICBhZHF1aXJpciBlbCBxdWUgc2UgYWRhcHRlIGEgc3VzIG5lY2VzaWRhZGVzLiBQcm9tdWV2ZSBlbCBwb3J0ZW8geSBsYVxuICAgICAgICAgICAgY3JpYW56YSByZXNwZXR1b3NhIGEgdHJhdmVzIGRlIGFzZXNvcmFtaWVudG9zIGdydXBhbGVzLCByb25kYXMsXG4gICAgICAgICAgICB0YWxsZXJlcyB5IGNsYXNlcyBkZSBiYWlsZXMgcG9ydGVhbmRvLlxuICAgICAgICAgIDwvcD5cbiAgICAgICAgPC9kaXY+XG5cbiAgICAgIDwvZGl2PlxuICAgICAgPHNwYW5cbiAgICAgICAgY2xhc3M9XCJhcnJvdyBib3VuY2UgYWxpZ24tdGV4dC1ib3R0b20gZC1ub25lIGQtbWQtaW5saW5lIHRleHQtY2VudGVyXCI+XG4gICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWFuZ2xlLWRvdWJsZS1kb3duIGFsaWduLXRleHQtYm90dG9tXCIgLz5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IHRleHQtY2VudGVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY29sXCI+XG4gICAgICAgIDxoMSBjbGFzcz1cIm5vc290cmFzLXRpdGxlXCI+Tm9zb3RyYXM8L2gxPlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvdyBub3NvdHJhcyB0ZXh0LWNlbnRlciBhbGlnbi1zZWxmLWNlbnRlclwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtMTJcIj5cbiAgICAgICAgPGltZyBhbHQ9XCIuLi5cIiBjbGFzcz1cImFsaWduLXNlbGYtY2VudGVyIG1yLTMgYWxlaW1nXCIgc3JjPXtlc3RlZml9IC8+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYSByb3dcIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwibWVkaWEtYm9keVwiPlxuICAgICAgICAgICAgICA8aDUgY2xhc3M9XCJtdC0wIG1iLTFcIj5Fc3RlZmk8L2g1PlxuICAgICAgICAgICAgICA8cD5cbiAgICAgICAgICAgICAgICBPcmdhbml6YWRvcmEgZGUgZXZlbnRvcy8gRG91bGEgLyBDb25zdWx0b3JhIGVuIHBvcnRlbyBkZSBDcmlhbnphXG4gICAgICAgICAgICAgICAgZW4gQnJhem9zLlxuICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lciBlc3BhY2lvXCI+XG4gICAgPGhyIC8+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGgxPk51ZXN0cm8gRXNwYWNpbzwvaDE+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvdyB2aXNpdGFcIj5cbiAgICAgIDxoNT5QYWN0YW1vcyB0dSB2aXNpdGEgY29uIHByZXZpbyBhdmlzbzwvaDU+XG5cbiAgICA8L2Rpdj5cbiAgICA8YnV0dG9uIHR5cGU9XCJidXR0b25cIiBjbGFzcz1cImJ0biBidG4tZGFuZ2VyXCI+XG4gICAgICA8YVxuICAgICAgICB0YXJnZXQ9XCJfYmxhbmtcIlxuICAgICAgICBocmVmPVwiaHR0cHM6Ly9hcGkud2hhdHNhcHAuY29tL3NlbmQ/cGhvbmU9NTQ5MzYyNDI2MDgzOSZ0ZXh0PU1lJTIwaW50ZXJlc2ElMjBwYWN0YXIlMjB1bmElMjBjaXRhXCI+XG4gICAgICAgIFBhY3RhciB2aXNpdGFcbiAgICAgIDwvYT5cbiAgICA8L2J1dHRvbj5cblxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgIDxpZnJhbWVcbiAgICAgICAgdGl0bGU9XCJtYXBhXCJcbiAgICAgICAgYWxsb3dGdWxsU2NyZWVuPVwiXCJcbiAgICAgICAgY2xhc3M9XCJtYXBcIlxuICAgICAgICBmcmFtZUJvcmRlcj1cIjBcIlxuICAgICAgICBoZWlnaHQ9XCI2MDBcIlxuICAgICAgICBzcmM9XCJodHRwczovL3d3dy5nb29nbGUuY29tL21hcHMvZW1iZWQ/cGI9ITFtMTghMW0xMiExbTMhMWQzNTQwLjQ3MDk0OTgwMzc5NiEyZC01OS4wMDQ3NjA4ODQ4NDg5NSEzZC0yNy40NTQ1OTM5ODI4OTcyMzchMm0zITFmMCEyZjAhM2YwITNtMiExaTEwMjQhMmk3NjghNGYxMy4xITNtMyExbTIhMXMweDk0NDUwYzg2NDc0ZTBjMjclM0EweDY2YTJiOWJjZjZiZmY1MjEhMnNDYW5nYWxsbysxMTM3JTJDK0gzNTA4K1Jlc2lzdGVuY2lhJTJDK0NoYWNvITVlMCEzbTIhMXNlcy00MTkhMnNhciE0djE1NTYxOTgzMTk0MTAhNW0yITFzZXMtNDE5ITJzYXJcIlxuICAgICAgICBzdHlsZXM9XCJib3JkZXI6MFwiXG4gICAgICAgIHdpZHRoPVwiODAwXCIgLz5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8aHIgLz5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG48L2Rpdj5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFNRSxXQUFXLDRCQUFDLENBQUMsQUFDWCxhQUFhLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBQ0QsQ0FBQyw0QkFBQyxDQUFDLEFBQ0QsZUFBZSxDQUFFLE9BQU8sQ0FDeEIsS0FBSyxDQUFFLE9BQU8sQ0FDZCxNQUFNLENBQUUsT0FBTyxBQUNqQixDQUFDLEFBQ0QsT0FBTyw0QkFBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLG9CQUFNLENBQUMsRUFBRSxDQUFDLFFBQVEsQUFDL0IsQ0FBQyxBQUVELFdBQVcsb0JBQU8sQ0FBQyxBQUNqQixFQUFFLENBQ0YsR0FBRyxDQUNILEdBQUcsQ0FDSCxHQUFHLENBQ0gsSUFBSSxBQUFDLENBQUMsQUFDSixTQUFTLENBQUUsV0FBVyxDQUFDLENBQUMsQUFDMUIsQ0FBQyxBQUNELEdBQUcsQUFBQyxDQUFDLEFBQ0gsU0FBUyxDQUFFLFdBQVcsS0FBSyxDQUFDLEFBQzlCLENBQUMsQUFDRCxHQUFHLEFBQUMsQ0FBQyxBQUNILFNBQVMsQ0FBRSxXQUFXLEtBQUssQ0FBQyxBQUM5QixDQUFDLEFBQ0gsQ0FBQyxBQUVELHFCQUFxQiw0QkFBQyxDQUFDLEFBQ3JCLFNBQVMsQ0FBRSxJQUFJLENBQUMsVUFBVSxBQUM1QixDQUFDLEFBQ0QsTUFBTSxBQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN6QixVQUFVLDRCQUFDLENBQUMsQUFDVixnQkFBZ0IsQ0FBRSxJQUFJLGlDQUFpQyxDQUFDLENBQ3hELGVBQWUsQ0FBRSxLQUFLLENBQ3RCLGlCQUFpQixDQUFFLFNBQVMsQ0FDNUIsS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsSUFBSSxDQUNaLE1BQU0sQ0FBRSxDQUFDLENBQUMsVUFBVSxDQUNwQixRQUFRLENBQUUsTUFBTSxDQUNoQixXQUFXLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDNUIsY0FBYyxDQUFFLENBQUMsQ0FBQyxVQUFVLENBQzVCLGFBQWEsQ0FBRSxDQUFDLENBQUMsVUFBVSxBQUM3QixDQUFDLEFBQ0QsTUFBTSw0QkFBQyxDQUFDLEFBQ04sVUFBVSxDQUFFLE1BQU0sQ0FDbEIsTUFBTSxDQUFFLEVBQUUsQ0FBQyxDQUFDLENBQ1osUUFBUSxDQUFFLFFBQVEsQ0FDbEIsR0FBRyxDQUFFLElBQUksQ0FDVCxJQUFJLENBQUUsSUFBSSxDQUNWLEtBQUssQ0FBRSxLQUFLLENBQ1osT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxDQUNULE9BQU8sQ0FBRSxDQUFDLENBQ1YsT0FBTyxDQUFFLE1BQU0sQ0FDZixVQUFVLENBQUUsTUFBTSxDQUNsQixPQUFPLENBQUUsR0FBRyxBQUNkLENBQUMsQUFFRCxvQkFBTSxDQUFDLEVBQUUsY0FBQyxDQUFDLEFBQ1QsV0FBVyxDQUFFLElBQUksQ0FDakIsU0FBUyxDQUFFLE1BQU0sQUFDbkIsQ0FBQyxBQUNELEtBQUssNEJBQUMsQ0FBQyxBQUNMLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLGNBQWMsQ0FBRSxJQUFJLENBQ3BCLFdBQVcsQ0FBRSxJQUFJLEFBQ25CLENBQUMsQUFFRCxPQUFPLDRCQUFDLENBQUMsQUFDUCxTQUFTLENBQUUsSUFBSSxDQUNmLFlBQVksQ0FBRSxJQUFJLEFBQ3BCLENBQUMsQUFDSCxDQUFDLEFBRUQsZUFBZSw0QkFBQyxDQUFDLEFBQ2YsT0FBTyxDQUFFLElBQUksQ0FDYixLQUFLLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLEFBQ3BDLENBQUMsQUFFRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLFVBQVUsNEJBQUMsQ0FBQyxBQUNWLGdCQUFnQixDQUFFLElBQUksaUNBQWlDLENBQUMsQ0FDeEQsZUFBZSxDQUFFLEtBQUssQ0FDdEIsaUJBQWlCLENBQUUsU0FBUyxDQUM1QixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxLQUFLLENBQ2IsTUFBTSxDQUFFLENBQUMsQ0FBQyxVQUFVLENBQ3BCLFFBQVEsQ0FBRSxNQUFNLENBQ2hCLFdBQVcsQ0FBRSxJQUFJLENBQUMsVUFBVSxDQUM1QixjQUFjLENBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDNUIsYUFBYSxDQUFFLENBQUMsQ0FBQyxVQUFVLEFBQzdCLENBQUMsQUFFRCxvQkFBTSxDQUFDLEVBQUUsY0FBQyxDQUFDLEFBQ1QsV0FBVyxDQUFFLENBQUMsQ0FDZCxTQUFTLENBQUUsSUFBSSxDQUFDLFVBQVUsQUFDNUIsQ0FBQyxBQUNELEtBQUssNEJBQUMsQ0FBQyxBQUNMLFNBQVMsQ0FBRSxJQUFJLENBQ2YsY0FBYyxDQUFFLElBQUksQ0FFcEIsYUFBYSxDQUFFLElBQUksQUFDckIsQ0FBQyxBQUVELE9BQU8sNEJBQUMsQ0FBQyxBQUNQLFNBQVMsQ0FBRSxLQUFLLENBQ2hCLFlBQVksQ0FBRSxJQUFJLEFBQ3BCLENBQUMsQUFDSCxDQUFDLEFBRUQsSUFBSSw0QkFBQyxDQUFDLEFBQ0osU0FBUyxDQUFFLElBQUksQ0FDZixLQUFLLENBQUUsS0FBSyxDQUFDLFVBQVUsQUFDekIsQ0FBQyxBQUVELGtCQUFrQiw0QkFBQyxDQUFDLEFBQ2xCLGNBQWMsQ0FBRSxXQUFXLENBQUMsVUFBVSxBQUN4QyxDQUFDLEFBRUQsTUFBTSw0QkFBQyxDQUFDLEFBQ04sT0FBTyxDQUFFLFdBQVcsQ0FDcEIsT0FBTyxDQUFFLEdBQUcsQ0FDWixPQUFPLENBQUUsSUFBSSxDQUNiLGNBQWMsQ0FBRSxLQUFLLENBQ3JCLFdBQVcsQ0FBRSxVQUFVLEFBQ3pCLENBQUMsQUFDRCxTQUFTLDRCQUFDLENBQUMsQUFDVCxPQUFPLENBQUUsSUFBSSxDQUNiLEtBQUssQ0FBRSxJQUFJLEdBQUcsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLFVBQVUsQUFDcEMsQ0FBQyxBQUVELFFBQVEsNEJBQUMsQ0FBQyxBQUNSLEtBQUssQ0FBRSxJQUFJLEdBQUcsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDbEMsY0FBYyxDQUFFLElBQUksQUFDdEIsQ0FBQyxBQUNELE9BQU8sNEJBQUMsQ0FBQyxBQUNQLE9BQU8sQ0FBRSxHQUFHLENBQ1osY0FBYyxDQUFFLEdBQUcsQUFDckIsQ0FBQyxBQUVELElBQUksNEJBQUMsQ0FBQyxBQUNKLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLElBQUksQUFDZCxDQUFDIn0= */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div18;
	let div4;
	let div3;
	let div2;
	let div0;
	let h10;
	let t0;
	let br;
	let t1;
	let t2;
	let div1;
	let p0;
	let t3;
	let t4;
	let span;
	let i;
	let t5;
	let div12;
	let div6;
	let div5;
	let h11;
	let t6;
	let t7;
	let div11;
	let div10;
	let img;
	let img_src_value;
	let t8;
	let div9;
	let div8;
	let div7;
	let h50;
	let t9;
	let t10;
	let p1;
	let t11;
	let t12;
	let div17;
	let hr0;
	let t13;
	let div13;
	let h12;
	let t14;
	let t15;
	let div14;
	let h51;
	let t16;
	let t17;
	let button;
	let a;
	let t18;
	let t19;
	let div15;
	let iframe;
	let iframe_src_value;
	let t20;
	let div16;
	let hr1;

	const block = {
		c: function create() {
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("¿Qué es\n            ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            Zarigüeya?");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Un espacio destinado a las familias donde podrán asesorarse en\n            porteo ergonomico, conocer diferentes modelos de portabebés y\n            adquirir el que se adapte a sus necesidades. Promueve el porteo y la\n            crianza respetuosa a traves de asesoramientos grupales, rondas,\n            talleres y clases de bailes porteando.");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nosotras");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Estefi");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Organizadora de eventos/ Doula / Consultora en porteo de Crianza\n                en Brazos.");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nuestro Espacio");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactamos tu visita con previo aviso");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactar visita");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("iframe");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			this.h();
		},
		l: function claim(nodes) {
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "DIV", { class: true });
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true });
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true });
			var h10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h10);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "¿Qué es\n            ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(h10_nodes, "BR", {});
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "\n            Zarigüeya?");
			h10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Un espacio destinado a las familias donde podrán asesorarse en\n            porteo ergonomico, conocer diferentes modelos de portabebés y\n            adquirir el que se adapte a sus necesidades. Promueve el porteo y la\n            crianza respetuosa a traves de asesoramientos grupales, rondas,\n            talleres y clases de bailes porteando.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div3_nodes);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "I", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div18_nodes);
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "DIV", { class: true });
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "DIV", { class: true });
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "H1", { class: true });
			var h11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h11);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h11_nodes, "Nosotras");
			h11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div12_nodes);
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "DIV", { class: true });
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "DIV", { class: true });
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "IMG", { alt: true, class: true, src: true });
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div10_nodes);
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "DIV", { class: true });
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div9_nodes, "DIV", { class: true });
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div8_nodes, "DIV", { class: true });
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "H5", { class: true });
			var h50_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h50);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h50_nodes, "Estefi");
			h50_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div7_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "P", {});
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Organizadora de eventos/ Doula / Consultora en porteo de Crianza\n                en Brazos.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div18_nodes);
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "DIV", { class: true });
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "HR", {});
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div13_nodes, "H1", {});
			var h12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h12);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h12_nodes, "Nuestro Espacio");
			h12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "H5", {});
			var h51_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h51);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h51_nodes, "Pactamos tu visita con previo aviso");
			h51_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "BUTTON", { type: true, class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(button_nodes, "A", { target: true, href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "Pactar visita");
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);

			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "IFRAME", {
				title: true,
				allowFullScreen: true,
				class: true,
				frameBorder: true,
				height: true,
				src: true,
				styles: true,
				width: true
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(iframe).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "HR", {});
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 160, 12, 2987);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h10, "class", " text-center svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h10, file, 158, 10, 2929);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "col-12 col-md-6 title pt-xs-10 svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 157, 8, 2874);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "lead text-center desc svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 165, 10, 3096);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 164, 8, 3056);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 156, 6, 2848);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-angle-double-down align-text-bottom svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 177, 8, 3630);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "arrow bounce align-text-bottom d-none d-md-inline text-center svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 175, 6, 3537);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "banner");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 155, 4, 2821);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "jumbotron svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 154, 2, 2793);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h11, "class", "nosotras-title svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h11, file, 184, 8, 3813);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "col");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 183, 6, 3787);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div6, "class", "row text-center");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 182, 4, 3751);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "alt", "...");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "class", "align-self-center mr-3 aleimg svelte-dych8n");
			if (img.src !== (img_src_value = /*estefi*/ ctx[0])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "src", img_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 189, 8, 3984);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h50, "class", "mt-0 mb-1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h50, file, 193, 14, 4167);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 194, 14, 4215);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div7, "class", "media-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 192, 12, 4128);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div8, "class", "col-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 191, 10, 4095);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div9, "class", "media row svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 190, 8, 4061);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div10, "class", "col-12 col-md-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 188, 6, 3945);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div11, "class", "row nosotras text-center align-self-center svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 187, 4, 3882);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div12, "class", "container");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 181, 2, 3723);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr0, file, 206, 4, 4469);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h12, file, 208, 6, 4504);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div13, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 207, 4, 4480);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h51, file, 211, 6, 4575);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div14, "class", "row visita svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 210, 4, 4544);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "https://api.whatsapp.com/send?phone=5493624260839&text=Me%20interesa%20pactar%20una%20cita");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 215, 6, 4688);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "type", "button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "btn btn-danger svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 214, 4, 4636);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "title", "mapa");
			iframe.allowFullscreen = "";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "class", "map svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "frameborder", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "height", "600");
			if (iframe.src !== (iframe_src_value = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3540.470949803796!2d-59.00476088484895!3d-27.454593982897237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450c86474e0c27%3A0x66a2b9bcf6bff521!2sCangallo+1137%2C+H3508+Resistencia%2C+Chaco!5e0!3m2!1ses-419!2sar!4v1556198319410!5m2!1ses-419!2sar")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "src", iframe_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "styles", "border:0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "width", "800");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(iframe, file, 223, 6, 4898);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div15, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 222, 4, 4874);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr1, file, 234, 6, 5428);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div16, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 233, 4, 5404);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div17, "class", "container espacio svelte-dych8n");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 205, 2, 4433);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div18, "class", "fullcontainer");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 153, 0, 2763);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div18, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, h10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, h11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h11, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div9, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, h50);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h50, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, hr0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, h12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h12, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, h51);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h51, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, button);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, iframe);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, hr1);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div18);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let ale = "assets/Images/about/ale.png";
	let estefi = "assets/Images/about/estefi.png";
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<AboutComponent> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("AboutComponent", $$slots, []);
	$$self.$capture_state = () => ({ ale, estefi });

	$$self.$inject_state = $$props => {
		if ("ale" in $$props) ale = $$props.ale;
		if ("estefi" in $$props) $$invalidate(0, estefi = $$props.estefi);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [estefi];
}

class AboutComponent extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-dych8n-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "AboutComponent",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (AboutComponent);


/***/ }),

/***/ "./src/routes/about.svelte":
/*!*********************************!*\
  !*** ./src/routes/about.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/AboutComponent.svelte */ "./src/components/AboutComponent.svelte");
/* src/routes/about.svelte generated by Svelte v3.24.0 */



const file = "src/routes/about.svelte";

function create_fragment(ctx) {
	let div;
	let aboutcomponent;
	let current;
	aboutcomponent = new _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(aboutcomponent.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true, id: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(aboutcomponent.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "containerfluid");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "id", "about");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 4, 0, 90);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(aboutcomponent, div, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(aboutcomponent.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(aboutcomponent.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(aboutcomponent);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<About> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("About", $$slots, []);
	$$self.$capture_state = () => ({ AboutComponent: _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"] });
	return [];
}

class About extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "About",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (About);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLi9zcmMvY29tcG9uZW50cy9BYm91dENvbXBvbmVudC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy8vLy4vc3JjL3JvdXRlcy9hYm91dC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7K0NBNkxrRSxHQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztLQTVMbEUsR0FBRyxHQUFHLDZCQUE2QjtLQUNuQyxNQUFNLEdBQUcsZ0NBQWdDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNEc0IiLCJmaWxlIjoiYzY0YjI1MjdlYjAwNzUzOWUyYWQvYWJvdXQuYWJvdXQuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBsZXQgYWxlID0gXCJhc3NldHMvSW1hZ2VzL2Fib3V0L2FsZS5wbmdcIjtcbiAgbGV0IGVzdGVmaSA9IFwiYXNzZXRzL0ltYWdlcy9hYm91dC9lc3RlZmkucG5nXCI7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICAuYnRuLWRhbmdlciB7XG4gICAgbWFyZ2luLWJvdHRvbTogMTBweDtcbiAgfVxuICBhIHtcbiAgICB0ZXh0LWRlY29yYXRpb246IGluaGVyaXQ7XG4gICAgY29sb3I6IGluaGVyaXQ7XG4gICAgY3Vyc29yOiBwb2ludGVyO1xuICB9XG4gIC5ib3VuY2Uge1xuICAgIGFuaW1hdGlvbjogYm91bmNlIDJzIGluZmluaXRlO1xuICB9XG5cbiAgQGtleWZyYW1lcyBib3VuY2Uge1xuICAgIDAlLFxuICAgIDIwJSxcbiAgICA1MCUsXG4gICAgODAlLFxuICAgIDEwMCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApO1xuICAgIH1cbiAgICA0MCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC0zMHB4KTtcbiAgICB9XG4gICAgNjAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMTVweCk7XG4gICAgfVxuICB9XG5cbiAgLmZhLWFuZ2xlLWRvdWJsZS1kb3duIHtcbiAgICBmb250LXNpemU6IDcwcHggIWltcG9ydGFudDtcbiAgfVxuICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHtcbiAgICAuanVtYm90cm9uIHtcbiAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybChcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXNwYWNpby5qcGdcIik7XG4gICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIGhlaWdodDogOTB2aDtcbiAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgIH1cbiAgICAuYXJyb3cge1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgbWFyZ2luOiA4JSAwO1xuICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgdG9wOiA4MHZoO1xuICAgICAgbGVmdDogNDh2dztcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIHBhZGRpbmc6IDA7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICB6LWluZGV4OiA0O1xuICAgICAgZGlzcGxheTogaW5saW5lO1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgb3BhY2l0eTogMC42O1xuICAgIH1cblxuICAgIC50aXRsZSBoMSB7XG4gICAgICBwYWRkaW5nLXRvcDogMjl2aDtcbiAgICAgIGZvbnQtc2l6ZTogNS41cmVtO1xuICAgIH1cbiAgICAubGVhZCB7XG4gICAgICBmb250LXNpemU6IDEuN3Z3O1xuICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICBwYWRkaW5nLXRvcDogMzB2aDtcbiAgICB9XG5cbiAgICAuYWxlaW1nIHtcbiAgICAgIG1heC13aWR0aDogMTJ2dztcbiAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICB9XG4gIH1cblxuICAubm9zb3RyYXMtdGl0bGUge1xuICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgfVxuXG4gIEBtZWRpYSAobWF4LXdpZHRoOiA3NjhweCkge1xuICAgIC5qdW1ib3Ryb24ge1xuICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKFwiYXNzZXRzL0ltYWdlcy9hYm91dC9lc3BhY2lvLmpwZ1wiKTtcbiAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gICAgICBiYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgaGVpZ2h0OiAxODB2dztcbiAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgIH1cblxuICAgIC50aXRsZSBoMSB7XG4gICAgICBwYWRkaW5nLXRvcDogMDtcbiAgICAgIGZvbnQtc2l6ZTogNjBweCAhaW1wb3J0YW50O1xuICAgIH1cbiAgICAubGVhZCB7XG4gICAgICBmb250LXNpemU6IDE4cHg7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMjBweDtcbiAgICAgIC8qIHBhZGRpbmctdG9wOiA7ICovXG4gICAgICBtYXJnaW4tYm90dG9tOiAyNXB4O1xuICAgIH1cblxuICAgIC5hbGVpbWcge1xuICAgICAgbWF4LXdpZHRoOiAxMDBweDtcbiAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICB9XG4gIH1cblxuICAuZmFzIHtcbiAgICBmb250LXNpemU6IDcwcHg7XG4gICAgY29sb3I6IHdoaXRlICFpbXBvcnRhbnQ7XG4gIH1cblxuICAuYWxpZ24tdGV4dC1ib3R0b20ge1xuICAgIHZlcnRpY2FsLWFsaWduOiB0ZXh0LWJvdHRvbSAhaW1wb3J0YW50O1xuICB9XG5cbiAgLm1lZGlhIHtcbiAgICBkaXNwbGF5OiAtbXMtZmxleGJveDtcbiAgICBwYWRkaW5nOiA1cHg7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICAtbXMtZmxleC1hbGlnbjogc3RhcnQ7XG4gICAgYWxpZ24taXRlbXM6IGZsZXgtc3RhcnQ7XG4gIH1cbiAgLm5vc290cmFzIHtcbiAgICBwYWRkaW5nOiAxNXB4O1xuICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gIH1cblxuICAuZXNwYWNpbyB7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgICBwYWRkaW5nLWJvdHRvbTogMTVweDtcbiAgfVxuICAudmlzaXRhIHtcbiAgICBvcGFjaXR5OiAwLjU7XG4gICAgcGFkZGluZy1ib3R0b206IDNweDtcbiAgfVxuXG4gIC5tYXAge1xuICAgIHdpZHRoOiAxMDB2dztcbiAgICBoZWlnaHQ6IDQwdmg7XG4gIH1cbjwvc3R5bGU+XG5cbjxkaXYgY2xhc3M9XCJmdWxsY29udGFpbmVyXCI+XG4gIDxkaXYgY2xhc3M9XCJqdW1ib3Ryb25cIj5cbiAgICA8ZGl2IGNsYXNzPVwiYmFubmVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTYgdGl0bGUgcHQteHMtMTBcIj5cbiAgICAgICAgICA8aDEgY2xhc3M9XCIgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgICAgIMK/UXXDqSBlc1xuICAgICAgICAgICAgPGJyIC8+XG4gICAgICAgICAgICBaYXJpZ8O8ZXlhP1xuICAgICAgICAgIDwvaDE+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC02XCI+XG4gICAgICAgICAgPHAgY2xhc3M9XCJsZWFkIHRleHQtY2VudGVyIGRlc2NcIj5cbiAgICAgICAgICAgIFVuIGVzcGFjaW8gZGVzdGluYWRvIGEgbGFzIGZhbWlsaWFzIGRvbmRlIHBvZHLDoW4gYXNlc29yYXJzZSBlblxuICAgICAgICAgICAgcG9ydGVvIGVyZ29ub21pY28sIGNvbm9jZXIgZGlmZXJlbnRlcyBtb2RlbG9zIGRlIHBvcnRhYmViw6lzIHlcbiAgICAgICAgICAgIGFkcXVpcmlyIGVsIHF1ZSBzZSBhZGFwdGUgYSBzdXMgbmVjZXNpZGFkZXMuIFByb211ZXZlIGVsIHBvcnRlbyB5IGxhXG4gICAgICAgICAgICBjcmlhbnphIHJlc3BldHVvc2EgYSB0cmF2ZXMgZGUgYXNlc29yYW1pZW50b3MgZ3J1cGFsZXMsIHJvbmRhcyxcbiAgICAgICAgICAgIHRhbGxlcmVzIHkgY2xhc2VzIGRlIGJhaWxlcyBwb3J0ZWFuZG8uXG4gICAgICAgICAgPC9wPlxuICAgICAgICA8L2Rpdj5cblxuICAgICAgPC9kaXY+XG4gICAgICA8c3BhblxuICAgICAgICBjbGFzcz1cImFycm93IGJvdW5jZSBhbGlnbi10ZXh0LWJvdHRvbSBkLW5vbmUgZC1tZC1pbmxpbmUgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtYW5nbGUtZG91YmxlLWRvd24gYWxpZ24tdGV4dC1ib3R0b21cIiAvPlxuICAgICAgPC9zcGFuPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgdGV4dC1jZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjb2xcIj5cbiAgICAgICAgPGgxIGNsYXNzPVwibm9zb3RyYXMtdGl0bGVcIj5Ob3NvdHJhczwvaDE+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IG5vc290cmFzIHRleHQtY2VudGVyIGFsaWduLXNlbGYtY2VudGVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC0xMlwiPlxuICAgICAgICA8aW1nIGFsdD1cIi4uLlwiIGNsYXNzPVwiYWxpZ24tc2VsZi1jZW50ZXIgbXItMyBhbGVpbWdcIiBzcmM9e2VzdGVmaX0gLz5cbiAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhIHJvd1wiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYS1ib2R5XCI+XG4gICAgICAgICAgICAgIDxoNSBjbGFzcz1cIm10LTAgbWItMVwiPkVzdGVmaTwvaDU+XG4gICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgIE9yZ2FuaXphZG9yYSBkZSBldmVudG9zLyBEb3VsYSAvIENvbnN1bHRvcmEgZW4gcG9ydGVvIGRlIENyaWFuemFcbiAgICAgICAgICAgICAgICBlbiBCcmF6b3MuXG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cblxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGVzcGFjaW9cIj5cbiAgICA8aHIgLz5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8aDE+TnVlc3RybyBFc3BhY2lvPC9oMT5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IHZpc2l0YVwiPlxuICAgICAgPGg1PlBhY3RhbW9zIHR1IHZpc2l0YSBjb24gcHJldmlvIGF2aXNvPC9oNT5cblxuICAgIDwvZGl2PlxuICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIGNsYXNzPVwiYnRuIGJ0bi1kYW5nZXJcIj5cbiAgICAgIDxhXG4gICAgICAgIHRhcmdldD1cIl9ibGFua1wiXG4gICAgICAgIGhyZWY9XCJodHRwczovL2FwaS53aGF0c2FwcC5jb20vc2VuZD9waG9uZT01NDkzNjI0MjYwODM5JnRleHQ9TWUlMjBpbnRlcmVzYSUyMHBhY3RhciUyMHVuYSUyMGNpdGFcIj5cbiAgICAgICAgUGFjdGFyIHZpc2l0YVxuICAgICAgPC9hPlxuICAgIDwvYnV0dG9uPlxuXG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGlmcmFtZVxuICAgICAgICB0aXRsZT1cIm1hcGFcIlxuICAgICAgICBhbGxvd0Z1bGxTY3JlZW49XCJcIlxuICAgICAgICBjbGFzcz1cIm1hcFwiXG4gICAgICAgIGZyYW1lQm9yZGVyPVwiMFwiXG4gICAgICAgIGhlaWdodD1cIjYwMFwiXG4gICAgICAgIHNyYz1cImh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vbWFwcy9lbWJlZD9wYj0hMW0xOCExbTEyITFtMyExZDM1NDAuNDcwOTQ5ODAzNzk2ITJkLTU5LjAwNDc2MDg4NDg0ODk1ITNkLTI3LjQ1NDU5Mzk4Mjg5NzIzNyEybTMhMWYwITJmMCEzZjAhM20yITFpMTAyNCEyaTc2OCE0ZjEzLjEhM20zITFtMiExczB4OTQ0NTBjODY0NzRlMGMyNyUzQTB4NjZhMmI5YmNmNmJmZjUyMSEyc0NhbmdhbGxvKzExMzclMkMrSDM1MDgrUmVzaXN0ZW5jaWElMkMrQ2hhY28hNWUwITNtMiExc2VzLTQxOSEyc2FyITR2MTU1NjE5ODMxOTQxMCE1bTIhMXNlcy00MTkhMnNhclwiXG4gICAgICAgIHN0eWxlcz1cImJvcmRlcjowXCJcbiAgICAgICAgd2lkdGg9XCI4MDBcIiAvPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgIDxociAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPHNjcmlwdD5cbiAgICBpbXBvcnQgQWJvdXRDb21wb25lbnQgZnJvbSAnLi4vY29tcG9uZW50cy9BYm91dENvbXBvbmVudC5zdmVsdGUnO1xuPC9zY3JpcHQ+XG5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJmbHVpZFwiIGlkPVwiYWJvdXRcIj5cbiAgICA8QWJvdXRDb21wb25lbnQgLz5cbjwvZGl2PlxuXG48c3R5bGU+XG5cbjwvc3R5bGU+XG4iXSwic291cmNlUm9vdCI6IiJ9