(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about"],{

/***/ "./src/components/AboutComponent.svelte":
/*!**********************************************!*\
  !*** ./src/components/AboutComponent.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/AboutComponent.svelte generated by Svelte v3.24.0 */


const file = "src/components/AboutComponent.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-ctwgfq-style";
	style.textContent = ".bounce.svelte-ctwgfq{animation:svelte-ctwgfq-bounce 2s infinite}@keyframes svelte-ctwgfq-bounce{0%,20%,50%,80%,100%{transform:translateY(0)}40%{transform:translateY(-30px)}60%{transform:translateY(-15px)}}.fa-angle-double-down.svelte-ctwgfq{font-size:70px !important}@media(min-width: 768px){.jumbotron.svelte-ctwgfq{background-image:url(\"assets/Images/about/espacio.jpg\");background-size:cover;background-repeat:no-repeat;color:white;height:90vh;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.arrow.svelte-ctwgfq{text-align:center;margin:8% 0;position:absolute;top:80vh;left:48vw;color:white;padding:0;margin:0;z-index:4;display:inline;text-align:center;opacity:0.6}.title.svelte-ctwgfq{padding-top:29vh}.lead.svelte-ctwgfq{font-size:1.7vw;padding-bottom:20px;padding-top:30vh}.aleimg.svelte-ctwgfq{max-width:12vw;padding-left:20px}}.nosotras-title.svelte-ctwgfq{padding:15px;color:rgb(190, 86, 89) !important}@media(max-width: 768px){.jumbotron.svelte-ctwgfq{background-image:url(\"assets/Images/about/espacio.jpg\");background-size:cover;background-repeat:no-repeat;color:white;height:auto;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.title.svelte-ctwgfq{padding-top:10vw}.lead.svelte-ctwgfq{font-size:1.7vw;padding-bottom:20px;padding-top:1vh;margin-bottom:25px}.aleimg.svelte-ctwgfq{max-width:100px;padding-left:20px}}.fas.svelte-ctwgfq{font-size:70px;color:white !important}.align-text-bottom.svelte-ctwgfq{vertical-align:text-bottom !important}.media.svelte-ctwgfq{display:-ms-flexbox;padding:5px;display:flex;-ms-flex-align:start;align-items:flex-start}.nosotras.svelte-ctwgfq{padding:15px;color:rgb(190, 86, 89) !important}.espacio.svelte-ctwgfq{color:rgb(190, 86, 89) !important;padding-bottom:15px}.visita.svelte-ctwgfq{opacity:0.5;padding-bottom:3px}.map.svelte-ctwgfq{width:100vw;height:40vh}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWJvdXRDb21wb25lbnQuc3ZlbHRlIiwic291cmNlcyI6WyJBYm91dENvbXBvbmVudC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGFsZSA9IFwiYXNzZXRzL0ltYWdlcy9hYm91dC9hbGUucG5nXCI7XG4gIGxldCBlc3RlZmkgPSBcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXN0ZWZpLnBuZ1wiO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLmJvdW5jZSB7XG4gICAgYW5pbWF0aW9uOiBib3VuY2UgMnMgaW5maW5pdGU7XG4gIH1cblxuICBAa2V5ZnJhbWVzIGJvdW5jZSB7XG4gICAgMCUsXG4gICAgMjAlLFxuICAgIDUwJSxcbiAgICA4MCUsXG4gICAgMTAwJSB7XG4gICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMCk7XG4gICAgfVxuICAgIDQwJSB7XG4gICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTMwcHgpO1xuICAgIH1cbiAgICA2MCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC0xNXB4KTtcbiAgICB9XG4gIH1cblxuICAuZmEtYW5nbGUtZG91YmxlLWRvd24ge1xuICAgIGZvbnQtc2l6ZTogNzBweCAhaW1wb3J0YW50O1xuICB9XG4gIEBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAgIC5qdW1ib3Ryb24ge1xuICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKFwiYXNzZXRzL0ltYWdlcy9hYm91dC9lc3BhY2lvLmpwZ1wiKTtcbiAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gICAgICBiYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgaGVpZ2h0OiA5MHZoO1xuICAgICAgbWFyZ2luOiAwICFpbXBvcnRhbnQ7XG4gICAgICBvdmVyZmxvdzogaGlkZGVuO1xuICAgICAgcGFkZGluZy10b3A6IDE1cHggIWltcG9ydGFudDtcbiAgICAgIHBhZGRpbmctYm90dG9tOiAwICFpbXBvcnRhbnQ7XG4gICAgICBib3JkZXItcmFkaXVzOiAwICFpbXBvcnRhbnQ7XG4gICAgfVxuICAgIC5hcnJvdyB7XG4gICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgICBtYXJnaW46IDglIDA7XG4gICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICB0b3A6IDgwdmg7XG4gICAgICBsZWZ0OiA0OHZ3O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgcGFkZGluZzogMDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIHotaW5kZXg6IDQ7XG4gICAgICBkaXNwbGF5OiBpbmxpbmU7XG4gICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgICBvcGFjaXR5OiAwLjY7XG4gICAgfVxuXG4gICAgLnRpdGxlIHtcbiAgICAgIHBhZGRpbmctdG9wOiAyOXZoO1xuICAgIH1cbiAgICAubGVhZCB7XG4gICAgICBmb250LXNpemU6IDEuN3Z3O1xuICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICBwYWRkaW5nLXRvcDogMzB2aDtcbiAgICB9XG5cbiAgICAuYWxlaW1nIHtcbiAgICAgIG1heC13aWR0aDogMTJ2dztcbiAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICB9XG4gIH1cblxuICAubm9zb3RyYXMtdGl0bGUge1xuICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgfVxuXG4gIEBtZWRpYSAobWF4LXdpZHRoOiA3NjhweCkge1xuICAgIC5qdW1ib3Ryb24ge1xuICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKFwiYXNzZXRzL0ltYWdlcy9hYm91dC9lc3BhY2lvLmpwZ1wiKTtcbiAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gICAgICBiYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgaGVpZ2h0OiBhdXRvO1xuICAgICAgbWFyZ2luOiAwICFpbXBvcnRhbnQ7XG4gICAgICBvdmVyZmxvdzogaGlkZGVuO1xuICAgICAgcGFkZGluZy10b3A6IDE1cHggIWltcG9ydGFudDtcbiAgICAgIHBhZGRpbmctYm90dG9tOiAwICFpbXBvcnRhbnQ7XG4gICAgICBib3JkZXItcmFkaXVzOiAwICFpbXBvcnRhbnQ7XG4gICAgfVxuXG4gICAgLnRpdGxlIHtcbiAgICAgIHBhZGRpbmctdG9wOiAxMHZ3O1xuICAgIH1cbiAgICAubGVhZCB7XG4gICAgICBmb250LXNpemU6IDEuN3Z3O1xuICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICBwYWRkaW5nLXRvcDogMXZoO1xuICAgICAgbWFyZ2luLWJvdHRvbTogMjVweDtcbiAgICB9XG5cbiAgICAuYWxlaW1nIHtcbiAgICAgIG1heC13aWR0aDogMTAwcHg7XG4gICAgICBwYWRkaW5nLWxlZnQ6IDIwcHg7XG4gICAgfVxuICB9XG5cbiAgLmZhcyB7XG4gICAgZm9udC1zaXplOiA3MHB4O1xuICAgIGNvbG9yOiB3aGl0ZSAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmFsaWduLXRleHQtYm90dG9tIHtcbiAgICB2ZXJ0aWNhbC1hbGlnbjogdGV4dC1ib3R0b20gIWltcG9ydGFudDtcbiAgfVxuXG4gIC5tZWRpYSB7XG4gICAgZGlzcGxheTogLW1zLWZsZXhib3g7XG4gICAgcGFkZGluZzogNXB4O1xuICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgLW1zLWZsZXgtYWxpZ246IHN0YXJ0O1xuICAgIGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0O1xuICB9XG4gIC5ub3NvdHJhcyB7XG4gICAgcGFkZGluZzogMTVweDtcbiAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICB9XG5cbiAgLmVzcGFjaW8ge1xuICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gICAgcGFkZGluZy1ib3R0b206IDE1cHg7XG4gIH1cbiAgLnZpc2l0YSB7XG4gICAgb3BhY2l0eTogMC41O1xuICAgIHBhZGRpbmctYm90dG9tOiAzcHg7XG4gIH1cblxuICAubWFwIHtcbiAgICB3aWR0aDogMTAwdnc7XG4gICAgaGVpZ2h0OiA0MHZoO1xuICB9XG48L3N0eWxlPlxuXG48ZGl2IGNsYXNzPVwiZnVsbGNvbnRhaW5lclwiPlxuICA8ZGl2IGNsYXNzPVwianVtYm90cm9uXCI+XG4gICAgPGRpdiBjbGFzcz1cImJhbm5lclwiPlxuICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC02IHRpdGxlIHB0LXhzLTEwXCI+XG4gICAgICAgICAgPGgxIGNsYXNzPVwiZGlzcGxheS0yIHRleHQtY2VudGVyIHRleHQtbWQtbGVmdFwiPlxuICAgICAgICAgICAgTnVlc3Ryb1xuICAgICAgICAgICAgPGJyIC8+XG4gICAgICAgICAgICBJbmljaW9cbiAgICAgICAgICA8L2gxPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNlwiPlxuICAgICAgICAgIDxwIGNsYXNzPVwibGVhZCBhbGlnbi10ZXh0LW1pZGRsZSBkZXNjXCI+XG4gICAgICAgICAgICBOYWNlIGRlIGRvcyBhbWlnYXMgY29uIGdhbmFzIGRlIGFjb21wYcOxYXIgYWwgYmViw6kgeSBzdSBmYW1pbGlhXG4gICAgICAgICAgICBkdXJhbnRlIGVsIG5hY2ltaWVudG8geSBjcmVjaW1pZW50byBwYXJhXG4gICAgICAgICAgICA8Yj5nZXN0YXI8L2I+XG4gICAgICAgICAgICBqdW50b3MgY29uc2NpZW5jaWEgc29icmVcbiAgICAgICAgICAgIDxiPmNyaWFuemE8L2I+XG4gICAgICAgICAgICByZXNwZXR1b3NhLlxuICAgICAgICAgICAgPGJyIC8+XG4gICAgICAgICAgICBTZW50aW1vcyB5IGVsZWdpbW9zIGhhY2VybG8gYnJpbmRhbmRvIGFzZXNvcmFtaWVudG8gc29icmVcbiAgICAgICAgICAgIDxiPnBvcnRlbzwvYj5cbiAgICAgICAgICAgIGVyZ29uw7NtaWNvICh0YW50byBwYXJ0aWN1bGFyZXMgY29tbyBncnVwYWxlcykgeSBhIHRyYXbDqXMgZGUgbGEgdmVudGFcbiAgICAgICAgICAgIGRlXG4gICAgICAgICAgICA8Yj5wb3J0YWJlYmVzIHkgYXJ0aWN1bG9zPC9iPlxuICAgICAgICAgICAgcmVzcGV0dW9zb3MgcGFyYSBsb3MgbmnDsW9zLlxuICAgICAgICAgIDwvcD5cbiAgICAgICAgPC9kaXY+XG5cbiAgICAgIDwvZGl2PlxuICAgICAgPHNwYW5cbiAgICAgICAgY2xhc3M9XCJhcnJvdyBib3VuY2UgYWxpZ24tdGV4dC1ib3R0b20gZC1ub25lIGQtbWQtaW5saW5lIHRleHQtY2VudGVyXCI+XG4gICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWFuZ2xlLWRvdWJsZS1kb3duIGFsaWduLXRleHQtYm90dG9tXCIgLz5cbiAgICAgIDwvc3Bhbj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG4gIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IHRleHQtY2VudGVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY29sXCI+XG4gICAgICAgIDxoMSBjbGFzcz1cIm5vc290cmFzLXRpdGxlXCI+Tm9zb3RyYXM8L2gxPlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvdyBub3NvdHJhcyB0ZXh0LWNlbnRlclwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNlwiPlxuICAgICAgICA8aW1nIGFsdD1cIi4uLlwiIGNsYXNzPVwiYWxpZ24tc2VsZi1jZW50ZXIgbXItMyBhbGVpbWdcIiBzcmM9e2FsZX0gLz5cbiAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhIHJvd1wiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYS1ib2R5XCI+XG4gICAgICAgICAgICAgIDxoNSBjbGFzcz1cIm10LTAgbWItMVwiPkFsZTwvaDU+XG4gICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgIEVzdHVkaWFudGUgYXZhbnphZGEgZGUgQWRtaW5pc3RyYWNpw7NuIGRlIEVtcHJlc2FzIHkgdHJhYmFqYSBjb21vXG4gICAgICAgICAgICAgICAgYWRtaW5pc3RyYXRpdmEgY29udGFibGUuXG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNlwiPlxuICAgICAgICA8aW1nIGFsdD1cIi4uLlwiIGNsYXNzPVwiYWxpZ24tc2VsZi1jZW50ZXIgbXItMyBhbGVpbWdcIiBzcmM9e2VzdGVmaX0gLz5cbiAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhIHJvd1wiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYS1ib2R5XCI+XG4gICAgICAgICAgICAgIDxoNSBjbGFzcz1cIm10LTAgbWItMVwiPkVzdGVmaTwvaDU+XG4gICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgIE9yZ2FuaXphZG9yYSBkZSBldmVudG9zLyBEb3VsYSAvIENvbnN1bHRvcmEgZW4gcG9ydGVvIGRlIENyaWFuemFcbiAgICAgICAgICAgICAgICBlbiBCcmF6b3MuXG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cblxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGVzcGFjaW9cIj5cbiAgICA8aHIgLz5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8aDE+TnVlc3RybyBFc3BhY2lvPC9oMT5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IHZpc2l0YVwiPlxuICAgICAgPGg1PlBhY3RhbW9zIHR1IHZpc2l0YSBjb24gcHJldmlvIGF2aXNvPC9oNT5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8aWZyYW1lXG4gICAgICAgIHRpdGxlPVwibWFwYVwiXG4gICAgICAgIGFsbG93RnVsbFNjcmVlbj1cIlwiXG4gICAgICAgIGNsYXNzPVwibWFwXCJcbiAgICAgICAgZnJhbWVCb3JkZXI9XCIwXCJcbiAgICAgICAgaGVpZ2h0PVwiNjAwXCJcbiAgICAgICAgc3JjPVwiaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS9tYXBzL2VtYmVkP3BiPSExbTE4ITFtMTIhMW0zITFkMzU0MC40NzA5NDk4MDM3OTYhMmQtNTkuMDA0NzYwODg0ODQ4OTUhM2QtMjcuNDU0NTkzOTgyODk3MjM3ITJtMyExZjAhMmYwITNmMCEzbTIhMWkxMDI0ITJpNzY4ITRmMTMuMSEzbTMhMW0yITFzMHg5NDQ1MGM4NjQ3NGUwYzI3JTNBMHg2NmEyYjliY2Y2YmZmNTIxITJzQ2FuZ2FsbG8rMTEzNyUyQytIMzUwOCtSZXNpc3RlbmNpYSUyQytDaGFjbyE1ZTAhM20yITFzZXMtNDE5ITJzYXIhNHYxNTU2MTk4MzE5NDEwITVtMiExc2VzLTQxOSEyc2FyXCJcbiAgICAgICAgc3R5bGVzPVwiYm9yZGVyOjBcIlxuICAgICAgICB3aWR0aD1cIjgwMFwiIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGhyIC8+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBTUUsT0FBTyxjQUFDLENBQUMsQUFDUCxTQUFTLENBQUUsb0JBQU0sQ0FBQyxFQUFFLENBQUMsUUFBUSxBQUMvQixDQUFDLEFBRUQsV0FBVyxvQkFBTyxDQUFDLEFBQ2pCLEVBQUUsQ0FDRixHQUFHLENBQ0gsR0FBRyxDQUNILEdBQUcsQ0FDSCxJQUFJLEFBQUMsQ0FBQyxBQUNKLFNBQVMsQ0FBRSxXQUFXLENBQUMsQ0FBQyxBQUMxQixDQUFDLEFBQ0QsR0FBRyxBQUFDLENBQUMsQUFDSCxTQUFTLENBQUUsV0FBVyxLQUFLLENBQUMsQUFDOUIsQ0FBQyxBQUNELEdBQUcsQUFBQyxDQUFDLEFBQ0gsU0FBUyxDQUFFLFdBQVcsS0FBSyxDQUFDLEFBQzlCLENBQUMsQUFDSCxDQUFDLEFBRUQscUJBQXFCLGNBQUMsQ0FBQyxBQUNyQixTQUFTLENBQUUsSUFBSSxDQUFDLFVBQVUsQUFDNUIsQ0FBQyxBQUNELE1BQU0sQUFBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekIsVUFBVSxjQUFDLENBQUMsQUFDVixnQkFBZ0IsQ0FBRSxJQUFJLGlDQUFpQyxDQUFDLENBQ3hELGVBQWUsQ0FBRSxLQUFLLENBQ3RCLGlCQUFpQixDQUFFLFNBQVMsQ0FDNUIsS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsSUFBSSxDQUNaLE1BQU0sQ0FBRSxDQUFDLENBQUMsVUFBVSxDQUNwQixRQUFRLENBQUUsTUFBTSxDQUNoQixXQUFXLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDNUIsY0FBYyxDQUFFLENBQUMsQ0FBQyxVQUFVLENBQzVCLGFBQWEsQ0FBRSxDQUFDLENBQUMsVUFBVSxBQUM3QixDQUFDLEFBQ0QsTUFBTSxjQUFDLENBQUMsQUFDTixVQUFVLENBQUUsTUFBTSxDQUNsQixNQUFNLENBQUUsRUFBRSxDQUFDLENBQUMsQ0FDWixRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsSUFBSSxDQUNULElBQUksQ0FBRSxJQUFJLENBQ1YsS0FBSyxDQUFFLEtBQUssQ0FDWixPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQ0FDVixPQUFPLENBQUUsTUFBTSxDQUNmLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLE9BQU8sQ0FBRSxHQUFHLEFBQ2QsQ0FBQyxBQUVELE1BQU0sY0FBQyxDQUFDLEFBQ04sV0FBVyxDQUFFLElBQUksQUFDbkIsQ0FBQyxBQUNELEtBQUssY0FBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLEtBQUssQ0FDaEIsY0FBYyxDQUFFLElBQUksQ0FDcEIsV0FBVyxDQUFFLElBQUksQUFDbkIsQ0FBQyxBQUVELE9BQU8sY0FBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLElBQUksQ0FDZixZQUFZLENBQUUsSUFBSSxBQUNwQixDQUFDLEFBQ0gsQ0FBQyxBQUVELGVBQWUsY0FBQyxDQUFDLEFBQ2YsT0FBTyxDQUFFLElBQUksQ0FDYixLQUFLLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLEFBQ3BDLENBQUMsQUFFRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLFVBQVUsY0FBQyxDQUFDLEFBQ1YsZ0JBQWdCLENBQUUsSUFBSSxpQ0FBaUMsQ0FBQyxDQUN4RCxlQUFlLENBQUUsS0FBSyxDQUN0QixpQkFBaUIsQ0FBRSxTQUFTLENBQzVCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLElBQUksQ0FDWixNQUFNLENBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDcEIsUUFBUSxDQUFFLE1BQU0sQ0FDaEIsV0FBVyxDQUFFLElBQUksQ0FBQyxVQUFVLENBQzVCLGNBQWMsQ0FBRSxDQUFDLENBQUMsVUFBVSxDQUM1QixhQUFhLENBQUUsQ0FBQyxDQUFDLFVBQVUsQUFDN0IsQ0FBQyxBQUVELE1BQU0sY0FBQyxDQUFDLEFBQ04sV0FBVyxDQUFFLElBQUksQUFDbkIsQ0FBQyxBQUNELEtBQUssY0FBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLEtBQUssQ0FDaEIsY0FBYyxDQUFFLElBQUksQ0FDcEIsV0FBVyxDQUFFLEdBQUcsQ0FDaEIsYUFBYSxDQUFFLElBQUksQUFDckIsQ0FBQyxBQUVELE9BQU8sY0FBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLEtBQUssQ0FDaEIsWUFBWSxDQUFFLElBQUksQUFDcEIsQ0FBQyxBQUNILENBQUMsQUFFRCxJQUFJLGNBQUMsQ0FBQyxBQUNKLFNBQVMsQ0FBRSxJQUFJLENBQ2YsS0FBSyxDQUFFLEtBQUssQ0FBQyxVQUFVLEFBQ3pCLENBQUMsQUFFRCxrQkFBa0IsY0FBQyxDQUFDLEFBQ2xCLGNBQWMsQ0FBRSxXQUFXLENBQUMsVUFBVSxBQUN4QyxDQUFDLEFBRUQsTUFBTSxjQUFDLENBQUMsQUFDTixPQUFPLENBQUUsV0FBVyxDQUNwQixPQUFPLENBQUUsR0FBRyxDQUNaLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLEtBQUssQ0FDckIsV0FBVyxDQUFFLFVBQVUsQUFDekIsQ0FBQyxBQUNELFNBQVMsY0FBQyxDQUFDLEFBQ1QsT0FBTyxDQUFFLElBQUksQ0FDYixLQUFLLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLEFBQ3BDLENBQUMsQUFFRCxRQUFRLGNBQUMsQ0FBQyxBQUNSLEtBQUssQ0FBRSxJQUFJLEdBQUcsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDbEMsY0FBYyxDQUFFLElBQUksQUFDdEIsQ0FBQyxBQUNELE9BQU8sY0FBQyxDQUFDLEFBQ1AsT0FBTyxDQUFFLEdBQUcsQ0FDWixjQUFjLENBQUUsR0FBRyxBQUNyQixDQUFDLEFBRUQsSUFBSSxjQUFDLENBQUMsQUFDSixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxJQUFJLEFBQ2QsQ0FBQyJ9 */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div22;
	let div4;
	let div3;
	let div2;
	let div0;
	let h10;
	let t0;
	let br0;
	let t1;
	let t2;
	let div1;
	let p0;
	let t3;
	let b0;
	let t4;
	let t5;
	let b1;
	let t6;
	let t7;
	let br1;
	let t8;
	let b2;
	let t9;
	let t10;
	let b3;
	let t11;
	let t12;
	let t13;
	let span;
	let i;
	let t14;
	let div16;
	let div6;
	let div5;
	let h11;
	let t15;
	let t16;
	let div15;
	let div10;
	let img0;
	let img0_src_value;
	let t17;
	let div9;
	let div8;
	let div7;
	let h50;
	let t18;
	let t19;
	let p1;
	let t20;
	let t21;
	let div14;
	let img1;
	let img1_src_value;
	let t22;
	let div13;
	let div12;
	let div11;
	let h51;
	let t23;
	let t24;
	let p2;
	let t25;
	let t26;
	let div21;
	let hr0;
	let t27;
	let div17;
	let h12;
	let t28;
	let t29;
	let div18;
	let h52;
	let t30;
	let t31;
	let div19;
	let iframe;
	let iframe_src_value;
	let t32;
	let div20;
	let hr1;

	const block = {
		c: function create() {
			div22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nuestro\n            ");
			br0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            Inicio");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nace de dos amigas con ganas de acompañar al bebé y su familia\n            durante el nacimiento y crecimiento para\n            ");
			b0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("gestar");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            juntos consciencia sobre\n            ");
			b1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("crianza");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            respetuosa.\n            ");
			br1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            Sentimos y elegimos hacerlo brindando asesoramiento sobre\n            ");
			b2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("porteo");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            ergonómico (tanto particulares como grupales) y a través de la venta\n            de\n            ");
			b3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("portabebes y articulos");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            respetuosos para los niños.");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nosotras");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Ale");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Estudiante avanzada de Administración de Empresas y trabaja como\n                administrativa contable.");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Estefi");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Organizadora de eventos/ Doula / Consultora en porteo de Crianza\n                en Brazos.");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nuestro Espacio");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h52 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactamos tu visita con previo aviso");
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("iframe");
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			this.h();
		},
		l: function claim(nodes) {
			div22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div22_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div22);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div22_nodes, "DIV", { class: true });
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true });
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true });
			var h10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h10);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "Nuestro\n            ");
			br0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(h10_nodes, "BR", {});
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "\n            Inicio");
			h10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Nace de dos amigas con ganas de acompañar al bebé y su familia\n            durante el nacimiento y crecimiento para\n            ");
			b0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b0);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b0_nodes, "gestar");
			b0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n            juntos consciencia sobre\n            ");
			b1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b1);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b1_nodes, "crianza");
			b1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n            respetuosa.\n            ");
			br1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "BR", {});
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n            Sentimos y elegimos hacerlo brindando asesoramiento sobre\n            ");
			b2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b2);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b2_nodes, "porteo");
			b2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n            ergonómico (tanto particulares como grupales) y a través de la venta\n            de\n            ");
			b3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b3);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b3_nodes, "portabebes y articulos");
			b3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n            respetuosos para los niños.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div3_nodes);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "I", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div22_nodes);
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div22_nodes, "DIV", { class: true });
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "DIV", { class: true });
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "H1", { class: true });
			var h11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h11);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h11_nodes, "Nosotras");
			h11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div16_nodes);
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "DIV", { class: true });
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "IMG", { alt: true, class: true, src: true });
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div10_nodes);
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "DIV", { class: true });
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div9_nodes, "DIV", { class: true });
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div8_nodes, "DIV", { class: true });
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "H5", { class: true });
			var h50_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h50);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h50_nodes, "Ale");
			h50_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div7_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "P", {});
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Estudiante avanzada de Administración de Empresas y trabaja como\n                administrativa contable.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div15_nodes);
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "IMG", { alt: true, class: true, src: true });
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div14_nodes);
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "DIV", { class: true });
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div13_nodes, "DIV", { class: true });
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "DIV", { class: true });
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "H5", { class: true });
			var h51_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h51);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h51_nodes, "Estefi");
			h51_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div11_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "P", {});
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Organizadora de eventos/ Doula / Consultora en porteo de Crianza\n                en Brazos.");
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div22_nodes);
			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div22_nodes, "DIV", { class: true });
			var div21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div21);
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "HR", {});
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "H1", {});
			var h12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h12);
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h12_nodes, "Nuestro Espacio");
			h12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);
			h52 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "H5", {});
			var h52_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h52);
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h52_nodes, "Pactamos tu visita con previo aviso");
			h52_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div19_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div19);

			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div19_nodes, "IFRAME", {
				title: true,
				allowFullScreen: true,
				class: true,
				frameBorder: true,
				height: true,
				src: true,
				styles: true,
				width: true
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(iframe).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div19_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div20);
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "HR", {});
			div20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div22_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br0, file, 150, 12, 2818);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h10, "class", "display-2 text-center text-md-left");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h10, file, 148, 10, 2738);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "col-12 col-md-6 title pt-xs-10 svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 147, 8, 2683);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b0, file, 158, 12, 3103);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b1, file, 160, 12, 3166);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br1, file, 162, 12, 3217);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b2, file, 164, 12, 3306);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b3, file, 167, 12, 3428);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "lead align-text-middle desc svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 155, 10, 2923);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 154, 8, 2883);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 146, 6, 2657);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-angle-double-down align-text-bottom svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 175, 8, 3641);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "arrow bounce align-text-bottom d-none d-md-inline text-center svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 173, 6, 3548);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "banner");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 145, 4, 2630);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "jumbotron svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 144, 2, 2602);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h11, "class", "nosotras-title svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h11, file, 182, 8, 3824);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "col");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 181, 6, 3798);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div6, "class", "row text-center");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 180, 4, 3762);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "alt", "...");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "class", "align-self-center mr-3 aleimg svelte-ctwgfq");
			if (img0.src !== (img0_src_value = /*ale*/ ctx[0])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "src", img0_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img0, file, 187, 8, 3976);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h50, "class", "mt-0 mb-1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h50, file, 191, 14, 4156);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 192, 14, 4201);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div7, "class", "media-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 190, 12, 4117);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div8, "class", "col-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 189, 10, 4084);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div9, "class", "media row svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 188, 8, 4050);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div10, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 186, 6, 3938);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "alt", "...");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "class", "align-self-center mr-3 aleimg svelte-ctwgfq");
			if (img1.src !== (img1_src_value = /*estefi*/ ctx[1])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "src", img1_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img1, file, 201, 8, 4454);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h51, "class", "mt-0 mb-1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h51, file, 205, 14, 4637);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 206, 14, 4685);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div11, "class", "media-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 204, 12, 4598);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div12, "class", "col-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 203, 10, 4565);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div13, "class", "media row svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 202, 8, 4531);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div14, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 200, 6, 4416);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div15, "class", "row nosotras text-center svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 185, 4, 3893);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div16, "class", "container");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 179, 2, 3734);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr0, file, 218, 4, 4939);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h12, file, 220, 6, 4974);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div17, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 219, 4, 4950);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h52, file, 223, 6, 5045);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div18, "class", "row visita svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 222, 4, 5014);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "title", "mapa");
			iframe.allowFullscreen = "";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "class", "map svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "frameborder", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "height", "600");
			if (iframe.src !== (iframe_src_value = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3540.470949803796!2d-59.00476088484895!3d-27.454593982897237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450c86474e0c27%3A0x66a2b9bcf6bff521!2sCangallo+1137%2C+H3508+Resistencia%2C+Chaco!5e0!3m2!1ses-419!2sar!4v1556198319410!5m2!1ses-419!2sar")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "src", iframe_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "styles", "border:0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "width", "800");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(iframe, file, 226, 6, 5129);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div19, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div19, file, 225, 4, 5105);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr1, file, 237, 6, 5659);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div20, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div20, file, 236, 4, 5635);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div21, "class", "container espacio svelte-ctwgfq");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div21, file, 217, 2, 4903);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div22, "class", "fullcontainer");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div22, file, 143, 0, 2572);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div22, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, h10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, br0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, br1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b2, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b3, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, h11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h11, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, img0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div9, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, h50);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h50, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, img1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, h51);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h51, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, div21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, hr0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, h12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h12, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t29);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, h52);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h52, t30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div19, iframe);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, hr1);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div22);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let ale = "assets/Images/about/ale.png";
	let estefi = "assets/Images/about/estefi.png";
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<AboutComponent> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("AboutComponent", $$slots, []);
	$$self.$capture_state = () => ({ ale, estefi });

	$$self.$inject_state = $$props => {
		if ("ale" in $$props) $$invalidate(0, ale = $$props.ale);
		if ("estefi" in $$props) $$invalidate(1, estefi = $$props.estefi);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [ale, estefi];
}

class AboutComponent extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-ctwgfq-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "AboutComponent",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (AboutComponent);


/***/ }),

/***/ "./src/routes/about.svelte":
/*!*********************************!*\
  !*** ./src/routes/about.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/AboutComponent.svelte */ "./src/components/AboutComponent.svelte");
/* src/routes/about.svelte generated by Svelte v3.24.0 */



const file = "src/routes/about.svelte";

function create_fragment(ctx) {
	let t;
	let div;
	let aboutcomponent;
	let current;
	aboutcomponent = new _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(aboutcomponent.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			const head_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["query_selector_all"])("[data-svelte=\"svelte-1myew8g\"]", document.head);
			head_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(nodes);
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(aboutcomponent.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			document.title = "About";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "containerfluid");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 11, 0, 159);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, t, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(aboutcomponent, div, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(aboutcomponent.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(aboutcomponent.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(t);
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(aboutcomponent);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<About> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("About", $$slots, []);
	$$self.$capture_state = () => ({ AboutComponent: _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"] });
	return [];
}

class About extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "About",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (About);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLy8vLi9zcmMvY29tcG9uZW50cy9BYm91dENvbXBvbmVudC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy8vLy4vc3JjL3JvdXRlcy9hYm91dC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzhDQTJMa0UsR0FBRzs7Ozs7Ozs7Ozs7Ozs7O2lEQWNILEdBQU07Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0tBeE1sRSxHQUFHLEdBQUcsNkJBQTZCO0tBQ25DLE1BQU0sR0FBRyxnQ0FBZ0M7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0RvQiIsImZpbGUiOiI5ZDc5Y2MxZjkwYjMyOTMwYThiZS9hYm91dC5hYm91dC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gIGxldCBhbGUgPSBcImFzc2V0cy9JbWFnZXMvYWJvdXQvYWxlLnBuZ1wiO1xuICBsZXQgZXN0ZWZpID0gXCJhc3NldHMvSW1hZ2VzL2Fib3V0L2VzdGVmaS5wbmdcIjtcbjwvc2NyaXB0PlxuXG48c3R5bGU+XG4gIC5ib3VuY2Uge1xuICAgIGFuaW1hdGlvbjogYm91bmNlIDJzIGluZmluaXRlO1xuICB9XG5cbiAgQGtleWZyYW1lcyBib3VuY2Uge1xuICAgIDAlLFxuICAgIDIwJSxcbiAgICA1MCUsXG4gICAgODAlLFxuICAgIDEwMCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApO1xuICAgIH1cbiAgICA0MCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC0zMHB4KTtcbiAgICB9XG4gICAgNjAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMTVweCk7XG4gICAgfVxuICB9XG5cbiAgLmZhLWFuZ2xlLWRvdWJsZS1kb3duIHtcbiAgICBmb250LXNpemU6IDcwcHggIWltcG9ydGFudDtcbiAgfVxuICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHtcbiAgICAuanVtYm90cm9uIHtcbiAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybChcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXNwYWNpby5qcGdcIik7XG4gICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIGhlaWdodDogOTB2aDtcbiAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgIH1cbiAgICAuYXJyb3cge1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgbWFyZ2luOiA4JSAwO1xuICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgdG9wOiA4MHZoO1xuICAgICAgbGVmdDogNDh2dztcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIHBhZGRpbmc6IDA7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICB6LWluZGV4OiA0O1xuICAgICAgZGlzcGxheTogaW5saW5lO1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgb3BhY2l0eTogMC42O1xuICAgIH1cblxuICAgIC50aXRsZSB7XG4gICAgICBwYWRkaW5nLXRvcDogMjl2aDtcbiAgICB9XG4gICAgLmxlYWQge1xuICAgICAgZm9udC1zaXplOiAxLjd2dztcbiAgICAgIHBhZGRpbmctYm90dG9tOiAyMHB4O1xuICAgICAgcGFkZGluZy10b3A6IDMwdmg7XG4gICAgfVxuXG4gICAgLmFsZWltZyB7XG4gICAgICBtYXgtd2lkdGg6IDEydnc7XG4gICAgICBwYWRkaW5nLWxlZnQ6IDIwcHg7XG4gICAgfVxuICB9XG5cbiAgLm5vc290cmFzLXRpdGxlIHtcbiAgICBwYWRkaW5nOiAxNXB4O1xuICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gIH1cblxuICBAbWVkaWEgKG1heC13aWR0aDogNzY4cHgpIHtcbiAgICAuanVtYm90cm9uIHtcbiAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybChcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXNwYWNpby5qcGdcIik7XG4gICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIGhlaWdodDogYXV0bztcbiAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgIH1cblxuICAgIC50aXRsZSB7XG4gICAgICBwYWRkaW5nLXRvcDogMTB2dztcbiAgICB9XG4gICAgLmxlYWQge1xuICAgICAgZm9udC1zaXplOiAxLjd2dztcbiAgICAgIHBhZGRpbmctYm90dG9tOiAyMHB4O1xuICAgICAgcGFkZGluZy10b3A6IDF2aDtcbiAgICAgIG1hcmdpbi1ib3R0b206IDI1cHg7XG4gICAgfVxuXG4gICAgLmFsZWltZyB7XG4gICAgICBtYXgtd2lkdGg6IDEwMHB4O1xuICAgICAgcGFkZGluZy1sZWZ0OiAyMHB4O1xuICAgIH1cbiAgfVxuXG4gIC5mYXMge1xuICAgIGZvbnQtc2l6ZTogNzBweDtcbiAgICBjb2xvcjogd2hpdGUgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5hbGlnbi10ZXh0LWJvdHRvbSB7XG4gICAgdmVydGljYWwtYWxpZ246IHRleHQtYm90dG9tICFpbXBvcnRhbnQ7XG4gIH1cblxuICAubWVkaWEge1xuICAgIGRpc3BsYXk6IC1tcy1mbGV4Ym94O1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIC1tcy1mbGV4LWFsaWduOiBzdGFydDtcbiAgICBhbGlnbi1pdGVtczogZmxleC1zdGFydDtcbiAgfVxuICAubm9zb3RyYXMge1xuICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5lc3BhY2lvIHtcbiAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICAgIHBhZGRpbmctYm90dG9tOiAxNXB4O1xuICB9XG4gIC52aXNpdGEge1xuICAgIG9wYWNpdHk6IDAuNTtcbiAgICBwYWRkaW5nLWJvdHRvbTogM3B4O1xuICB9XG5cbiAgLm1hcCB7XG4gICAgd2lkdGg6IDEwMHZ3O1xuICAgIGhlaWdodDogNDB2aDtcbiAgfVxuPC9zdHlsZT5cblxuPGRpdiBjbGFzcz1cImZ1bGxjb250YWluZXJcIj5cbiAgPGRpdiBjbGFzcz1cImp1bWJvdHJvblwiPlxuICAgIDxkaXYgY2xhc3M9XCJiYW5uZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNiB0aXRsZSBwdC14cy0xMFwiPlxuICAgICAgICAgIDxoMSBjbGFzcz1cImRpc3BsYXktMiB0ZXh0LWNlbnRlciB0ZXh0LW1kLWxlZnRcIj5cbiAgICAgICAgICAgIE51ZXN0cm9cbiAgICAgICAgICAgIDxiciAvPlxuICAgICAgICAgICAgSW5pY2lvXG4gICAgICAgICAgPC9oMT5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTZcIj5cbiAgICAgICAgICA8cCBjbGFzcz1cImxlYWQgYWxpZ24tdGV4dC1taWRkbGUgZGVzY1wiPlxuICAgICAgICAgICAgTmFjZSBkZSBkb3MgYW1pZ2FzIGNvbiBnYW5hcyBkZSBhY29tcGHDsWFyIGFsIGJlYsOpIHkgc3UgZmFtaWxpYVxuICAgICAgICAgICAgZHVyYW50ZSBlbCBuYWNpbWllbnRvIHkgY3JlY2ltaWVudG8gcGFyYVxuICAgICAgICAgICAgPGI+Z2VzdGFyPC9iPlxuICAgICAgICAgICAganVudG9zIGNvbnNjaWVuY2lhIHNvYnJlXG4gICAgICAgICAgICA8Yj5jcmlhbnphPC9iPlxuICAgICAgICAgICAgcmVzcGV0dW9zYS5cbiAgICAgICAgICAgIDxiciAvPlxuICAgICAgICAgICAgU2VudGltb3MgeSBlbGVnaW1vcyBoYWNlcmxvIGJyaW5kYW5kbyBhc2Vzb3JhbWllbnRvIHNvYnJlXG4gICAgICAgICAgICA8Yj5wb3J0ZW88L2I+XG4gICAgICAgICAgICBlcmdvbsOzbWljbyAodGFudG8gcGFydGljdWxhcmVzIGNvbW8gZ3J1cGFsZXMpIHkgYSB0cmF2w6lzIGRlIGxhIHZlbnRhXG4gICAgICAgICAgICBkZVxuICAgICAgICAgICAgPGI+cG9ydGFiZWJlcyB5IGFydGljdWxvczwvYj5cbiAgICAgICAgICAgIHJlc3BldHVvc29zIHBhcmEgbG9zIG5pw7Fvcy5cbiAgICAgICAgICA8L3A+XG4gICAgICAgIDwvZGl2PlxuXG4gICAgICA8L2Rpdj5cbiAgICAgIDxzcGFuXG4gICAgICAgIGNsYXNzPVwiYXJyb3cgYm91bmNlIGFsaWduLXRleHQtYm90dG9tIGQtbm9uZSBkLW1kLWlubGluZSB0ZXh0LWNlbnRlclwiPlxuICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1hbmdsZS1kb3VibGUtZG93biBhbGlnbi10ZXh0LWJvdHRvbVwiIC8+XG4gICAgICA8L3NwYW4+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cInJvdyB0ZXh0LWNlbnRlclwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbFwiPlxuICAgICAgICA8aDEgY2xhc3M9XCJub3NvdHJhcy10aXRsZVwiPk5vc290cmFzPC9oMT5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgbm9zb3RyYXMgdGV4dC1jZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTZcIj5cbiAgICAgICAgPGltZyBhbHQ9XCIuLi5cIiBjbGFzcz1cImFsaWduLXNlbGYtY2VudGVyIG1yLTMgYWxlaW1nXCIgc3JjPXthbGV9IC8+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYSByb3dcIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwibWVkaWEtYm9keVwiPlxuICAgICAgICAgICAgICA8aDUgY2xhc3M9XCJtdC0wIG1iLTFcIj5BbGU8L2g1PlxuICAgICAgICAgICAgICA8cD5cbiAgICAgICAgICAgICAgICBFc3R1ZGlhbnRlIGF2YW56YWRhIGRlIEFkbWluaXN0cmFjacOzbiBkZSBFbXByZXNhcyB5IHRyYWJhamEgY29tb1xuICAgICAgICAgICAgICAgIGFkbWluaXN0cmF0aXZhIGNvbnRhYmxlLlxuICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2Rpdj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTZcIj5cbiAgICAgICAgPGltZyBhbHQ9XCIuLi5cIiBjbGFzcz1cImFsaWduLXNlbGYtY2VudGVyIG1yLTMgYWxlaW1nXCIgc3JjPXtlc3RlZml9IC8+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYSByb3dcIj5cbiAgICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwibWVkaWEtYm9keVwiPlxuICAgICAgICAgICAgICA8aDUgY2xhc3M9XCJtdC0wIG1iLTFcIj5Fc3RlZmk8L2g1PlxuICAgICAgICAgICAgICA8cD5cbiAgICAgICAgICAgICAgICBPcmdhbml6YWRvcmEgZGUgZXZlbnRvcy8gRG91bGEgLyBDb25zdWx0b3JhIGVuIHBvcnRlbyBkZSBDcmlhbnphXG4gICAgICAgICAgICAgICAgZW4gQnJhem9zLlxuICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgPC9kaXY+XG5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lciBlc3BhY2lvXCI+XG4gICAgPGhyIC8+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGgxPk51ZXN0cm8gRXNwYWNpbzwvaDE+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvdyB2aXNpdGFcIj5cbiAgICAgIDxoNT5QYWN0YW1vcyB0dSB2aXNpdGEgY29uIHByZXZpbyBhdmlzbzwvaDU+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGlmcmFtZVxuICAgICAgICB0aXRsZT1cIm1hcGFcIlxuICAgICAgICBhbGxvd0Z1bGxTY3JlZW49XCJcIlxuICAgICAgICBjbGFzcz1cIm1hcFwiXG4gICAgICAgIGZyYW1lQm9yZGVyPVwiMFwiXG4gICAgICAgIGhlaWdodD1cIjYwMFwiXG4gICAgICAgIHNyYz1cImh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vbWFwcy9lbWJlZD9wYj0hMW0xOCExbTEyITFtMyExZDM1NDAuNDcwOTQ5ODAzNzk2ITJkLTU5LjAwNDc2MDg4NDg0ODk1ITNkLTI3LjQ1NDU5Mzk4Mjg5NzIzNyEybTMhMWYwITJmMCEzZjAhM20yITFpMTAyNCEyaTc2OCE0ZjEzLjEhM20zITFtMiExczB4OTQ0NTBjODY0NzRlMGMyNyUzQTB4NjZhMmI5YmNmNmJmZjUyMSEyc0NhbmdhbGxvKzExMzclMkMrSDM1MDgrUmVzaXN0ZW5jaWElMkMrQ2hhY28hNWUwITNtMiExc2VzLTQxOSEyc2FyITR2MTU1NjE5ODMxOTQxMCE1bTIhMXNlcy00MTkhMnNhclwiXG4gICAgICAgIHN0eWxlcz1cImJvcmRlcjowXCJcbiAgICAgICAgd2lkdGg9XCI4MDBcIiAvPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgIDxociAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvZGl2PlxuIiwiPHNjcmlwdD5cbiAgaW1wb3J0IEFib3V0Q29tcG9uZW50IGZyb20gXCIuLi9jb21wb25lbnRzL0Fib3V0Q29tcG9uZW50LnN2ZWx0ZVwiO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cblxuPC9zdHlsZT5cblxuPHN2ZWx0ZTpoZWFkPlxuICA8dGl0bGU+QWJvdXQ8L3RpdGxlPlxuPC9zdmVsdGU6aGVhZD5cbjxkaXYgY2xhc3M9XCJjb250YWluZXJmbHVpZFwiPlxuICA8QWJvdXRDb21wb25lbnQgLz5cbjwvZGl2PlxuIl0sInNvdXJjZVJvb3QiOiIifQ==