(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about"],{

/***/ "./src/components/AboutComponent.svelte":
/*!**********************************************!*\
  !*** ./src/components/AboutComponent.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/AboutComponent.svelte generated by Svelte v3.24.0 */


const file = "src/components/AboutComponent.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-qx6dgy-style";
	style.textContent = ".btn-danger.svelte-qx6dgy.svelte-qx6dgy{margin-bottom:10px}a.svelte-qx6dgy.svelte-qx6dgy{text-decoration:inherit;color:inherit;cursor:pointer}.bounce.svelte-qx6dgy.svelte-qx6dgy{animation:svelte-qx6dgy-bounce 2s infinite}@keyframes svelte-qx6dgy-bounce{0%,20%,50%,80%,100%{transform:translateY(0)}40%{transform:translateY(-30px)}60%{transform:translateY(-15px)}}.fa-angle-double-down.svelte-qx6dgy.svelte-qx6dgy{font-size:70px !important}@media(min-width: 768px){.jumbotron.svelte-qx6dgy.svelte-qx6dgy{background-image:url('assets/Images/about/espacio.jpg');background-size:cover;background-repeat:no-repeat;color:white;height:90vh;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.arrow.svelte-qx6dgy.svelte-qx6dgy{text-align:center;margin:8% 0;position:absolute;top:80vh;left:48vw;color:white;padding:0;margin:0;z-index:4;display:inline;text-align:center;opacity:0.6}.title.svelte-qx6dgy h1.svelte-qx6dgy{padding-top:29vh;font-size:5.5rem}.lead.svelte-qx6dgy.svelte-qx6dgy{font-size:1.7vw;padding-bottom:20px;padding-top:30vh}.aleimg.svelte-qx6dgy.svelte-qx6dgy{max-width:12vw;padding-left:20px}}.nosotras-title.svelte-qx6dgy.svelte-qx6dgy{padding:15px;color:rgb(190, 86, 89) !important}@media(max-width: 768px){.jumbotron.svelte-qx6dgy.svelte-qx6dgy{background-image:url('assets/Images/about/espacio.jpg');background-size:cover;background-repeat:no-repeat;color:white;height:180vw;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.title.svelte-qx6dgy h1.svelte-qx6dgy{padding-top:0;font-size:70px !important}.lead.svelte-qx6dgy.svelte-qx6dgy{font-size:18px;padding-bottom:20px;margin-bottom:25px}.aleimg.svelte-qx6dgy.svelte-qx6dgy{max-width:100px;padding-left:20px}}.fas.svelte-qx6dgy.svelte-qx6dgy{font-size:70px;color:white !important}.align-text-bottom.svelte-qx6dgy.svelte-qx6dgy{vertical-align:text-bottom !important}.media.svelte-qx6dgy.svelte-qx6dgy{display:-ms-flexbox;padding:5px;display:flex;-ms-flex-align:start;align-items:flex-start}.nosotras.svelte-qx6dgy.svelte-qx6dgy{padding:15px;color:rgb(190, 86, 89) !important}.espacio.svelte-qx6dgy.svelte-qx6dgy{color:rgb(190, 86, 89) !important;padding-bottom:15px}.visita.svelte-qx6dgy.svelte-qx6dgy{opacity:0.5;padding-bottom:3px}.map.svelte-qx6dgy.svelte-qx6dgy{width:100vw;height:40vh}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWJvdXRDb21wb25lbnQuc3ZlbHRlIiwic291cmNlcyI6WyJBYm91dENvbXBvbmVudC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgICBsZXQgYWxlID0gJ2Fzc2V0cy9JbWFnZXMvYWJvdXQvYWxlLnBuZyc7XG4gICAgbGV0IGVzdGVmaSA9ICdhc3NldHMvSW1hZ2VzL2Fib3V0L2VzdGVmaS5wbmcnO1xuPC9zY3JpcHQ+XG5cbjxkaXYgY2xhc3M9XCJmdWxsY29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cImp1bWJvdHJvblwiPlxuICAgICAgICA8ZGl2IGNsYXNzPVwiYmFubmVyXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNiB0aXRsZSBwdC14cy0xMFwiPlxuICAgICAgICAgICAgICAgICAgICA8aDEgY2xhc3M9XCIgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIE51ZXN0cm9cbiAgICAgICAgICAgICAgICAgICAgICAgIDxiciAvPlxuICAgICAgICAgICAgICAgICAgICAgICAgSW5pY2lvXG4gICAgICAgICAgICAgICAgICAgIDwvaDE+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNlwiPlxuICAgICAgICAgICAgICAgICAgICA8cCBjbGFzcz1cImxlYWQgdGV4dC1jZW50ZXIgZGVzY1wiPlxuICAgICAgICAgICAgICAgICAgICAgICAgTmFjZSBkZSBkb3MgYW1pZ2FzIGNvbiBnYW5hcyBkZSBhY29tcGHDsWFyIGFsIGJlYsOpIHkgc3UgZmFtaWxpYSBkdXJhbnRlIGVsXG4gICAgICAgICAgICAgICAgICAgICAgICBuYWNpbWllbnRvIHkgY3JlY2ltaWVudG8gcGFyYVxuICAgICAgICAgICAgICAgICAgICAgICAgPGI+Z2VzdGFyPC9iPlxuICAgICAgICAgICAgICAgICAgICAgICAganVudG9zIGNvbnNjaWVuY2lhIHNvYnJlXG4gICAgICAgICAgICAgICAgICAgICAgICA8Yj5jcmlhbnphPC9iPlxuICAgICAgICAgICAgICAgICAgICAgICAgcmVzcGV0dW9zYS5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxiciAvPlxuICAgICAgICAgICAgICAgICAgICAgICAgU2VudGltb3MgeSBlbGVnaW1vcyBoYWNlcmxvIGJyaW5kYW5kbyBhc2Vzb3JhbWllbnRvIHNvYnJlXG4gICAgICAgICAgICAgICAgICAgICAgICA8Yj5wb3J0ZW88L2I+XG4gICAgICAgICAgICAgICAgICAgICAgICBlcmdvbsOzbWljbyAodGFudG8gcGFydGljdWxhcmVzIGNvbW8gZ3J1cGFsZXMpIHkgYSB0cmF2w6lzIGRlIGxhIHZlbnRhIGRlXG4gICAgICAgICAgICAgICAgICAgICAgICA8Yj5wb3J0YWJlYmVzIHkgYXJ0aWN1bG9zPC9iPlxuICAgICAgICAgICAgICAgICAgICAgICAgcmVzcGV0dW9zb3MgcGFyYSBsb3MgbmnDsW9zLlxuICAgICAgICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgPHNwYW4gY2xhc3M9XCJhcnJvdyBib3VuY2UgYWxpZ24tdGV4dC1ib3R0b20gZC1ub25lIGQtbWQtaW5saW5lIHRleHQtY2VudGVyXCI+XG4gICAgICAgICAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtYW5nbGUtZG91YmxlLWRvd24gYWxpZ24tdGV4dC1ib3R0b21cIj48L2k+XG4gICAgICAgICAgICA8L3NwYW4+XG4gICAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXJcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvdyB0ZXh0LWNlbnRlclwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cImNvbFwiPlxuICAgICAgICAgICAgICAgIDxoMSBjbGFzcz1cIm5vc290cmFzLXRpdGxlXCI+Tm9zb3RyYXM8L2gxPlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93IG5vc290cmFzIHRleHQtY2VudGVyXCI+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC02XCI+XG4gICAgICAgICAgICAgICAgPGltZyBhbHQ9XCIuLi5cIiBjbGFzcz1cImFsaWduLXNlbGYtY2VudGVyIG1yLTMgYWxlaW1nXCIgc3JjPVwie2FsZX1cIiAvPlxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYSByb3dcIj5cbiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMlwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhLWJvZHlcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aDUgY2xhc3M9XCJtdC0wIG1iLTFcIj5BbGU8L2g1PlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBFc3R1ZGlhbnRlIGF2YW56YWRhIGRlIEFkbWluaXN0cmFjacOzbiBkZSBFbXByZXNhcyB5IHRyYWJhamEgY29tb1xuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBhZG1pbmlzdHJhdGl2YSBjb250YWJsZS5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTZcIj5cbiAgICAgICAgICAgICAgICA8aW1nIGFsdD1cIi4uLlwiIGNsYXNzPVwiYWxpZ24tc2VsZi1jZW50ZXIgbXItMyBhbGVpbWdcIiBzcmM9XCJ7ZXN0ZWZpfVwiIC8+XG4gICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhIHJvd1wiPlxuICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwibWVkaWEtYm9keVwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxoNSBjbGFzcz1cIm10LTAgbWItMVwiPkVzdGVmaTwvaDU+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPHA+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIE9yZ2FuaXphZG9yYSBkZSBldmVudG9zLyBEb3VsYSAvIENvbnN1bHRvcmEgZW4gcG9ydGVvIGRlIENyaWFuemEgZW5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgQnJhem9zLlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cblxuICAgIDxkaXYgY2xhc3M9XCJjb250YWluZXIgZXNwYWNpb1wiPlxuICAgICAgICA8aHIgLz5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICAgICAgPGgxPk51ZXN0cm8gRXNwYWNpbzwvaDE+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93IHZpc2l0YVwiPlxuICAgICAgICAgICAgPGg1PlBhY3RhbW9zIHR1IHZpc2l0YSBjb24gcHJldmlvIGF2aXNvPC9oNT5cblxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGJ1dHRvbiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiPlxuICAgICAgICAgICAgPGFcbiAgICAgICAgICAgICAgICB0YXJnZXQ9XCJfYmxhbmtcIlxuICAgICAgICAgICAgICAgIGhyZWY9XCJodHRwczovL2FwaS53aGF0c2FwcC5jb20vc2VuZD9waG9uZT01NDkzNjI0MjYwODM5JnRleHQ9TWUlMjBpbnRlcmVzYSUyMHBhY3RhciUyMHVuYSUyMGNpdGFcIlxuICAgICAgICAgICAgPlxuICAgICAgICAgICAgICAgIFBhY3RhciB2aXNpdGFcbiAgICAgICAgICAgIDwvYT5cbiAgICAgICAgPC9idXR0b24+XG5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICAgICAgPGlmcmFtZVxuICAgICAgICAgICAgICAgIHRpdGxlPVwibWFwYVwiXG4gICAgICAgICAgICAgICAgYWxsb3dGdWxsU2NyZWVuPVwiXCJcbiAgICAgICAgICAgICAgICBjbGFzcz1cIm1hcFwiXG4gICAgICAgICAgICAgICAgZnJhbWVCb3JkZXI9XCIwXCJcbiAgICAgICAgICAgICAgICBoZWlnaHQ9XCI2MDBcIlxuICAgICAgICAgICAgICAgIHNyYz1cImh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vbWFwcy9lbWJlZD9wYj0hMW0xOCExbTEyITFtMyExZDM1NDAuNDcwOTQ5ODAzNzk2ITJkLTU5LjAwNDc2MDg4NDg0ODk1ITNkLTI3LjQ1NDU5Mzk4Mjg5NzIzNyEybTMhMWYwITJmMCEzZjAhM20yITFpMTAyNCEyaTc2OCE0ZjEzLjEhM20zITFtMiExczB4OTQ0NTBjODY0NzRlMGMyNyUzQTB4NjZhMmI5YmNmNmJmZjUyMSEyc0NhbmdhbGxvKzExMzclMkMrSDM1MDgrUmVzaXN0ZW5jaWElMkMrQ2hhY28hNWUwITNtMiExc2VzLTQxOSEyc2FyITR2MTU1NjE5ODMxOTQxMCE1bTIhMXNlcy00MTkhMnNhclwiXG4gICAgICAgICAgICAgICAgc3R5bGVzPVwiYm9yZGVyOjBcIlxuICAgICAgICAgICAgICAgIHdpZHRoPVwiODAwXCJcbiAgICAgICAgICAgID48L2lmcmFtZT5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxociAvPlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbjwvZGl2PlxuXG48c3R5bGU+XG4gICAgLmJ0bi1kYW5nZXIge1xuICAgICAgICBtYXJnaW4tYm90dG9tOiAxMHB4O1xuICAgIH1cbiAgICBhIHtcbiAgICAgICAgdGV4dC1kZWNvcmF0aW9uOiBpbmhlcml0O1xuICAgICAgICBjb2xvcjogaW5oZXJpdDtcbiAgICAgICAgY3Vyc29yOiBwb2ludGVyO1xuICAgIH1cbiAgICAuYm91bmNlIHtcbiAgICAgICAgYW5pbWF0aW9uOiBib3VuY2UgMnMgaW5maW5pdGU7XG4gICAgfVxuXG4gICAgQGtleWZyYW1lcyBib3VuY2Uge1xuICAgICAgICAwJSxcbiAgICAgICAgMjAlLFxuICAgICAgICA1MCUsXG4gICAgICAgIDgwJSxcbiAgICAgICAgMTAwJSB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoMCk7XG4gICAgICAgIH1cbiAgICAgICAgNDAlIHtcbiAgICAgICAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMzBweCk7XG4gICAgICAgIH1cbiAgICAgICAgNjAlIHtcbiAgICAgICAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMTVweCk7XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICAuZmEtYW5nbGUtZG91YmxlLWRvd24ge1xuICAgICAgICBmb250LXNpemU6IDcwcHggIWltcG9ydGFudDtcbiAgICB9XG4gICAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgICAgIC5qdW1ib3Ryb24ge1xuICAgICAgICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKCdhc3NldHMvSW1hZ2VzL2Fib3V0L2VzcGFjaW8uanBnJyk7XG4gICAgICAgICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgICAgICAgIGhlaWdodDogOTB2aDtcbiAgICAgICAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgICAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICAgICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgICAgICB9XG4gICAgICAgIC5hcnJvdyB7XG4gICAgICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgICAgICAgICBtYXJnaW46IDglIDA7XG4gICAgICAgICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICAgICAgICB0b3A6IDgwdmg7XG4gICAgICAgICAgICBsZWZ0OiA0OHZ3O1xuICAgICAgICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgICAgICAgcGFkZGluZzogMDtcbiAgICAgICAgICAgIG1hcmdpbjogMDtcbiAgICAgICAgICAgIHotaW5kZXg6IDQ7XG4gICAgICAgICAgICBkaXNwbGF5OiBpbmxpbmU7XG4gICAgICAgICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgICAgICAgICBvcGFjaXR5OiAwLjY7XG4gICAgICAgIH1cblxuICAgICAgICAudGl0bGUgaDEge1xuICAgICAgICAgICAgcGFkZGluZy10b3A6IDI5dmg7XG4gICAgICAgICAgICBmb250LXNpemU6IDUuNXJlbTtcbiAgICAgICAgfVxuICAgICAgICAubGVhZCB7XG4gICAgICAgICAgICBmb250LXNpemU6IDEuN3Z3O1xuICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICAgICAgICBwYWRkaW5nLXRvcDogMzB2aDtcbiAgICAgICAgfVxuXG4gICAgICAgIC5hbGVpbWcge1xuICAgICAgICAgICAgbWF4LXdpZHRoOiAxMnZ3O1xuICAgICAgICAgICAgcGFkZGluZy1sZWZ0OiAyMHB4O1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgLm5vc290cmFzLXRpdGxlIHtcbiAgICAgICAgcGFkZGluZzogMTVweDtcbiAgICAgICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgICB9XG5cbiAgICBAbWVkaWEgKG1heC13aWR0aDogNzY4cHgpIHtcbiAgICAgICAgLmp1bWJvdHJvbiB7XG4gICAgICAgICAgICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoJ2Fzc2V0cy9JbWFnZXMvYWJvdXQvZXNwYWNpby5qcGcnKTtcbiAgICAgICAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gICAgICAgICAgICBiYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0O1xuICAgICAgICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgICAgICAgaGVpZ2h0OiAxODB2dztcbiAgICAgICAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgICAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICAgICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgICAgICB9XG5cbiAgICAgICAgLnRpdGxlIGgxIHtcbiAgICAgICAgICAgIHBhZGRpbmctdG9wOiAwO1xuICAgICAgICAgICAgZm9udC1zaXplOiA3MHB4ICFpbXBvcnRhbnQ7XG4gICAgICAgIH1cbiAgICAgICAgLmxlYWQge1xuICAgICAgICAgICAgZm9udC1zaXplOiAxOHB4O1xuICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICAgICAgICAvKiBwYWRkaW5nLXRvcDogOyAqL1xuICAgICAgICAgICAgbWFyZ2luLWJvdHRvbTogMjVweDtcbiAgICAgICAgfVxuXG4gICAgICAgIC5hbGVpbWcge1xuICAgICAgICAgICAgbWF4LXdpZHRoOiAxMDBweDtcbiAgICAgICAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICAgICAgfVxuICAgIH1cblxuICAgIC5mYXMge1xuICAgICAgICBmb250LXNpemU6IDcwcHg7XG4gICAgICAgIGNvbG9yOiB3aGl0ZSAhaW1wb3J0YW50O1xuICAgIH1cblxuICAgIC5hbGlnbi10ZXh0LWJvdHRvbSB7XG4gICAgICAgIHZlcnRpY2FsLWFsaWduOiB0ZXh0LWJvdHRvbSAhaW1wb3J0YW50O1xuICAgIH1cblxuICAgIC5tZWRpYSB7XG4gICAgICAgIGRpc3BsYXk6IC1tcy1mbGV4Ym94O1xuICAgICAgICBwYWRkaW5nOiA1cHg7XG4gICAgICAgIGRpc3BsYXk6IGZsZXg7XG4gICAgICAgIC1tcy1mbGV4LWFsaWduOiBzdGFydDtcbiAgICAgICAgYWxpZ24taXRlbXM6IGZsZXgtc3RhcnQ7XG4gICAgfVxuICAgIC5ub3NvdHJhcyB7XG4gICAgICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gICAgfVxuXG4gICAgLmVzcGFjaW8ge1xuICAgICAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICAgICAgICBwYWRkaW5nLWJvdHRvbTogMTVweDtcbiAgICB9XG4gICAgLnZpc2l0YSB7XG4gICAgICAgIG9wYWNpdHk6IDAuNTtcbiAgICAgICAgcGFkZGluZy1ib3R0b206IDNweDtcbiAgICB9XG5cbiAgICAubWFwIHtcbiAgICAgICAgd2lkdGg6IDEwMHZ3O1xuICAgICAgICBoZWlnaHQ6IDQwdmg7XG4gICAgfVxuPC9zdHlsZT5cbiJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiQUFrSEksV0FBVyw0QkFBQyxDQUFDLEFBQ1QsYUFBYSxDQUFFLElBQUksQUFDdkIsQ0FBQyxBQUNELENBQUMsNEJBQUMsQ0FBQyxBQUNDLGVBQWUsQ0FBRSxPQUFPLENBQ3hCLEtBQUssQ0FBRSxPQUFPLENBQ2QsTUFBTSxDQUFFLE9BQU8sQUFDbkIsQ0FBQyxBQUNELE9BQU8sNEJBQUMsQ0FBQyxBQUNMLFNBQVMsQ0FBRSxvQkFBTSxDQUFDLEVBQUUsQ0FBQyxRQUFRLEFBQ2pDLENBQUMsQUFFRCxXQUFXLG9CQUFPLENBQUMsQUFDZixFQUFFLENBQ0YsR0FBRyxDQUNILEdBQUcsQ0FDSCxHQUFHLENBQ0gsSUFBSSxBQUFDLENBQUMsQUFDRixTQUFTLENBQUUsV0FBVyxDQUFDLENBQUMsQUFDNUIsQ0FBQyxBQUNELEdBQUcsQUFBQyxDQUFDLEFBQ0QsU0FBUyxDQUFFLFdBQVcsS0FBSyxDQUFDLEFBQ2hDLENBQUMsQUFDRCxHQUFHLEFBQUMsQ0FBQyxBQUNELFNBQVMsQ0FBRSxXQUFXLEtBQUssQ0FBQyxBQUNoQyxDQUFDLEFBQ0wsQ0FBQyxBQUVELHFCQUFxQiw0QkFBQyxDQUFDLEFBQ25CLFNBQVMsQ0FBRSxJQUFJLENBQUMsVUFBVSxBQUM5QixDQUFDLEFBQ0QsTUFBTSxBQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN2QixVQUFVLDRCQUFDLENBQUMsQUFDUixnQkFBZ0IsQ0FBRSxJQUFJLGlDQUFpQyxDQUFDLENBQ3hELGVBQWUsQ0FBRSxLQUFLLENBQ3RCLGlCQUFpQixDQUFFLFNBQVMsQ0FDNUIsS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsSUFBSSxDQUNaLE1BQU0sQ0FBRSxDQUFDLENBQUMsVUFBVSxDQUNwQixRQUFRLENBQUUsTUFBTSxDQUNoQixXQUFXLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDNUIsY0FBYyxDQUFFLENBQUMsQ0FBQyxVQUFVLENBQzVCLGFBQWEsQ0FBRSxDQUFDLENBQUMsVUFBVSxBQUMvQixDQUFDLEFBQ0QsTUFBTSw0QkFBQyxDQUFDLEFBQ0osVUFBVSxDQUFFLE1BQU0sQ0FDbEIsTUFBTSxDQUFFLEVBQUUsQ0FBQyxDQUFDLENBQ1osUUFBUSxDQUFFLFFBQVEsQ0FDbEIsR0FBRyxDQUFFLElBQUksQ0FDVCxJQUFJLENBQUUsSUFBSSxDQUNWLEtBQUssQ0FBRSxLQUFLLENBQ1osT0FBTyxDQUFFLENBQUMsQ0FDVixNQUFNLENBQUUsQ0FBQyxDQUNULE9BQU8sQ0FBRSxDQUFDLENBQ1YsT0FBTyxDQUFFLE1BQU0sQ0FDZixVQUFVLENBQUUsTUFBTSxDQUNsQixPQUFPLENBQUUsR0FBRyxBQUNoQixDQUFDLEFBRUQsb0JBQU0sQ0FBQyxFQUFFLGNBQUMsQ0FBQyxBQUNQLFdBQVcsQ0FBRSxJQUFJLENBQ2pCLFNBQVMsQ0FBRSxNQUFNLEFBQ3JCLENBQUMsQUFDRCxLQUFLLDRCQUFDLENBQUMsQUFDSCxTQUFTLENBQUUsS0FBSyxDQUNoQixjQUFjLENBQUUsSUFBSSxDQUNwQixXQUFXLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBRUQsT0FBTyw0QkFBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLElBQUksQ0FDZixZQUFZLENBQUUsSUFBSSxBQUN0QixDQUFDLEFBQ0wsQ0FBQyxBQUVELGVBQWUsNEJBQUMsQ0FBQyxBQUNiLE9BQU8sQ0FBRSxJQUFJLENBQ2IsS0FBSyxDQUFFLElBQUksR0FBRyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsVUFBVSxBQUN0QyxDQUFDLEFBRUQsTUFBTSxBQUFDLFlBQVksS0FBSyxDQUFDLEFBQUMsQ0FBQyxBQUN2QixVQUFVLDRCQUFDLENBQUMsQUFDUixnQkFBZ0IsQ0FBRSxJQUFJLGlDQUFpQyxDQUFDLENBQ3hELGVBQWUsQ0FBRSxLQUFLLENBQ3RCLGlCQUFpQixDQUFFLFNBQVMsQ0FDNUIsS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsS0FBSyxDQUNiLE1BQU0sQ0FBRSxDQUFDLENBQUMsVUFBVSxDQUNwQixRQUFRLENBQUUsTUFBTSxDQUNoQixXQUFXLENBQUUsSUFBSSxDQUFDLFVBQVUsQ0FDNUIsY0FBYyxDQUFFLENBQUMsQ0FBQyxVQUFVLENBQzVCLGFBQWEsQ0FBRSxDQUFDLENBQUMsVUFBVSxBQUMvQixDQUFDLEFBRUQsb0JBQU0sQ0FBQyxFQUFFLGNBQUMsQ0FBQyxBQUNQLFdBQVcsQ0FBRSxDQUFDLENBQ2QsU0FBUyxDQUFFLElBQUksQ0FBQyxVQUFVLEFBQzlCLENBQUMsQUFDRCxLQUFLLDRCQUFDLENBQUMsQUFDSCxTQUFTLENBQUUsSUFBSSxDQUNmLGNBQWMsQ0FBRSxJQUFJLENBRXBCLGFBQWEsQ0FBRSxJQUFJLEFBQ3ZCLENBQUMsQUFFRCxPQUFPLDRCQUFDLENBQUMsQUFDTCxTQUFTLENBQUUsS0FBSyxDQUNoQixZQUFZLENBQUUsSUFBSSxBQUN0QixDQUFDLEFBQ0wsQ0FBQyxBQUVELElBQUksNEJBQUMsQ0FBQyxBQUNGLFNBQVMsQ0FBRSxJQUFJLENBQ2YsS0FBSyxDQUFFLEtBQUssQ0FBQyxVQUFVLEFBQzNCLENBQUMsQUFFRCxrQkFBa0IsNEJBQUMsQ0FBQyxBQUNoQixjQUFjLENBQUUsV0FBVyxDQUFDLFVBQVUsQUFDMUMsQ0FBQyxBQUVELE1BQU0sNEJBQUMsQ0FBQyxBQUNKLE9BQU8sQ0FBRSxXQUFXLENBQ3BCLE9BQU8sQ0FBRSxHQUFHLENBQ1osT0FBTyxDQUFFLElBQUksQ0FDYixjQUFjLENBQUUsS0FBSyxDQUNyQixXQUFXLENBQUUsVUFBVSxBQUMzQixDQUFDLEFBQ0QsU0FBUyw0QkFBQyxDQUFDLEFBQ1AsT0FBTyxDQUFFLElBQUksQ0FDYixLQUFLLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLEFBQ3RDLENBQUMsQUFFRCxRQUFRLDRCQUFDLENBQUMsQUFDTixLQUFLLENBQUUsSUFBSSxHQUFHLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxFQUFFLENBQUMsQ0FBQyxVQUFVLENBQ2xDLGNBQWMsQ0FBRSxJQUFJLEFBQ3hCLENBQUMsQUFDRCxPQUFPLDRCQUFDLENBQUMsQUFDTCxPQUFPLENBQUUsR0FBRyxDQUNaLGNBQWMsQ0FBRSxHQUFHLEFBQ3ZCLENBQUMsQUFFRCxJQUFJLDRCQUFDLENBQUMsQUFDRixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxJQUFJLEFBQ2hCLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div22;
	let div4;
	let div3;
	let div2;
	let div0;
	let h10;
	let t0;
	let br0;
	let t1;
	let t2;
	let div1;
	let p0;
	let t3;
	let b0;
	let t4;
	let t5;
	let b1;
	let t6;
	let t7;
	let br1;
	let t8;
	let b2;
	let t9;
	let t10;
	let b3;
	let t11;
	let t12;
	let t13;
	let span;
	let i;
	let t14;
	let div16;
	let div6;
	let div5;
	let h11;
	let t15;
	let t16;
	let div15;
	let div10;
	let img0;
	let img0_src_value;
	let t17;
	let div9;
	let div8;
	let div7;
	let h50;
	let t18;
	let t19;
	let p1;
	let t20;
	let t21;
	let div14;
	let img1;
	let img1_src_value;
	let t22;
	let div13;
	let div12;
	let div11;
	let h51;
	let t23;
	let t24;
	let p2;
	let t25;
	let t26;
	let div21;
	let hr0;
	let t27;
	let div17;
	let h12;
	let t28;
	let t29;
	let div18;
	let h52;
	let t30;
	let t31;
	let button;
	let a;
	let t32;
	let t33;
	let div19;
	let iframe;
	let iframe_src_value;
	let t34;
	let div20;
	let hr1;

	const block = {
		c: function create() {
			div22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nuestro\n                        ");
			br0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n                        Inicio");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nace de dos amigas con ganas de acompañar al bebé y su familia durante el\n                        nacimiento y crecimiento para\n                        ");
			b0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("gestar");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n                        juntos consciencia sobre\n                        ");
			b1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("crianza");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n                        respetuosa.\n                        ");
			br1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n                        Sentimos y elegimos hacerlo brindando asesoramiento sobre\n                        ");
			b2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("porteo");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n                        ergonómico (tanto particulares como grupales) y a través de la venta de\n                        ");
			b3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("b");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("portabebes y articulos");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n                        respetuosos para los niños.");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nosotras");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Ale");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Estudiante avanzada de Administración de Empresas y trabaja como\n                                administrativa contable.");
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Estefi");
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Organizadora de eventos/ Doula / Consultora en porteo de Crianza en\n                                Brazos.");
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nuestro Espacio");
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h52 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactamos tu visita con previo aviso");
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactar visita");
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("iframe");
			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			this.h();
		},
		l: function claim(nodes) {
			div22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div22_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div22);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div22_nodes, "DIV", { class: true });
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true });
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true });
			var h10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h10);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "Nuestro\n                        ");
			br0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(h10_nodes, "BR", {});
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "\n                        Inicio");
			h10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Nace de dos amigas con ganas de acompañar al bebé y su familia durante el\n                        nacimiento y crecimiento para\n                        ");
			b0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b0);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b0_nodes, "gestar");
			b0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n                        juntos consciencia sobre\n                        ");
			b1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b1);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b1_nodes, "crianza");
			b1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n                        respetuosa.\n                        ");
			br1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "BR", {});
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n                        Sentimos y elegimos hacerlo brindando asesoramiento sobre\n                        ");
			b2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b2);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b2_nodes, "porteo");
			b2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n                        ergonómico (tanto particulares como grupales) y a través de la venta de\n                        ");
			b3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(p0_nodes, "B", {});
			var b3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(b3);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(b3_nodes, "portabebes y articulos");
			b3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "\n                        respetuosos para los niños.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div3_nodes);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "I", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div22_nodes);
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div22_nodes, "DIV", { class: true });
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "DIV", { class: true });
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "H1", { class: true });
			var h11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h11);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h11_nodes, "Nosotras");
			h11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div16_nodes);
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "DIV", { class: true });
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);
			img0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "IMG", { alt: true, class: true, src: true });
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div10_nodes);
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "DIV", { class: true });
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div9_nodes, "DIV", { class: true });
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div8_nodes, "DIV", { class: true });
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "H5", { class: true });
			var h50_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h50);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h50_nodes, "Ale");
			h50_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div7_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "P", {});
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Estudiante avanzada de Administración de Empresas y trabaja como\n                                administrativa contable.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div15_nodes);
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "DIV", { class: true });
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);
			img1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "IMG", { alt: true, class: true, src: true });
			t22 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div14_nodes);
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "DIV", { class: true });
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div13_nodes, "DIV", { class: true });
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "DIV", { class: true });
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "H5", { class: true });
			var h51_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h51);
			t23 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h51_nodes, "Estefi");
			h51_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t24 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div11_nodes);
			p2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "P", {});
			var p2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p2);
			t25 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p2_nodes, "Organizadora de eventos/ Doula / Consultora en porteo de Crianza en\n                                Brazos.");
			p2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t26 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div22_nodes);
			div21 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div22_nodes, "DIV", { class: true });
			var div21_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div21);
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "HR", {});
			t27 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "H1", {});
			var h12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h12);
			t28 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h12_nodes, "Nuestro Espacio");
			h12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t29 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);
			h52 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "H5", {});
			var h52_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h52);
			t30 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h52_nodes, "Pactamos tu visita con previo aviso");
			h52_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t31 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "BUTTON", { type: true, class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(button_nodes, "A", { target: true, href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			t32 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "Pactar visita");
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t33 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div19_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div19);

			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div19_nodes, "IFRAME", {
				title: true,
				allowFullScreen: true,
				class: true,
				frameBorder: true,
				height: true,
				src: true,
				styles: true,
				width: true
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(iframe).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div19_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t34 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div21_nodes);
			div20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div21_nodes, "DIV", { class: true });
			var div20_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div20);
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div20_nodes, "HR", {});
			div20_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div21_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div22_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br0, file, 12, 24, 394);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h10, "class", " text-center svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h10, file, 10, 20, 312);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "col-12 col-md-6 title pt-xs-10 svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 9, 16, 247);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b0, file, 20, 24, 757);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b1, file, 22, 24, 844);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br1, file, 24, 24, 919);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b2, file, 26, 24, 1032);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(b3, file, 28, 24, 1166);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "lead text-center desc svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 17, 20, 547);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 16, 16, 497);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 8, 12, 213);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-angle-double-down align-text-bottom svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 35, 16, 1421);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "arrow bounce align-text-bottom d-none d-md-inline text-center svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 34, 12, 1328);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "banner");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 7, 8, 180);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "jumbotron svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 6, 4, 148);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h11, "class", "nosotras-title svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h11, file, 42, 16, 1638);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "col");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 41, 12, 1604);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div6, "class", "row text-center");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 40, 8, 1562);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "alt", "...");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "class", "align-self-center mr-3 aleimg svelte-qx6dgy");
			if (img0.src !== (img0_src_value = /*ale*/ ctx[0])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img0, "src", img0_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img0, file, 47, 16, 1818);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h50, "class", "mt-0 mb-1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h50, file, 51, 28, 2044);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 52, 28, 2103);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div7, "class", "media-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 50, 24, 1991);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div8, "class", "col-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 49, 20, 1946);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div9, "class", "media row svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 48, 16, 1902);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div10, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 46, 12, 1772);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "alt", "...");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "class", "align-self-center mr-3 aleimg svelte-qx6dgy");
			if (img1.src !== (img1_src_value = /*estefi*/ ctx[1])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img1, "src", img1_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img1, file, 61, 16, 2452);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h51, "class", "mt-0 mb-1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h51, file, 65, 28, 2681);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p2, file, 66, 28, 2743);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div11, "class", "media-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 64, 24, 2628);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div12, "class", "col-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 63, 20, 2583);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div13, "class", "media row svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 62, 16, 2539);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div14, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 60, 12, 2406);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div15, "class", "row nosotras text-center svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 45, 8, 1721);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div16, "class", "container");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 39, 4, 1530);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr0, file, 78, 8, 3091);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h12, file, 80, 12, 3136);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div17, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 79, 8, 3106);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h52, file, 83, 12, 3221);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div18, "class", "row visita svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 82, 8, 3184);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "https://api.whatsapp.com/send?phone=5493624260839&text=Me%20interesa%20pactar%20una%20cita");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 87, 12, 3348);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "type", "button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "btn btn-danger svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 86, 8, 3290);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "title", "mapa");
			iframe.allowFullscreen = "";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "class", "map svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "frameborder", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "height", "600");
			if (iframe.src !== (iframe_src_value = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3540.470949803796!2d-59.00476088484895!3d-27.454593982897237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450c86474e0c27%3A0x66a2b9bcf6bff521!2sCangallo+1137%2C+H3508+Resistencia%2C+Chaco!5e0!3m2!1ses-419!2sar!4v1556198319410!5m2!1ses-419!2sar")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "src", iframe_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "styles", "border:0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "width", "800");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(iframe, file, 96, 12, 3615);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div19, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div19, file, 95, 8, 3585);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr1, file, 108, 12, 4243);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div20, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div20, file, 107, 8, 4213);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div21, "class", "container espacio svelte-qx6dgy");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div21, file, 77, 4, 3051);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div22, "class", "fullcontainer");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div22, file, 5, 0, 116);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div22, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, h10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, br0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b0, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b1, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, br1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b2, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, b3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(b3, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, h11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h11, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, img0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div9, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, h50);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h50, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, t21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, img1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, t22);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, h51);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h51, t23);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, t24);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, p2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p2, t25);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, t26);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div22, div21);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, hr0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t27);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, h12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h12, t28);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t29);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, h52);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h52, t30);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t31);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, button);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, t32);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t33);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div19, iframe);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, t34);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div21, div20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div20, hr1);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div22);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let ale = "assets/Images/about/ale.png";
	let estefi = "assets/Images/about/estefi.png";
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<AboutComponent> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("AboutComponent", $$slots, []);
	$$self.$capture_state = () => ({ ale, estefi });

	$$self.$inject_state = $$props => {
		if ("ale" in $$props) $$invalidate(0, ale = $$props.ale);
		if ("estefi" in $$props) $$invalidate(1, estefi = $$props.estefi);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [ale, estefi];
}

class AboutComponent extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-qx6dgy-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "AboutComponent",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (AboutComponent);


/***/ }),

/***/ "./src/routes/about.svelte":
/*!*********************************!*\
  !*** ./src/routes/about.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/AboutComponent.svelte */ "./src/components/AboutComponent.svelte");
/* src/routes/about.svelte generated by Svelte v3.24.0 */



const file = "src/routes/about.svelte";

function create_fragment(ctx) {
	let div;
	let aboutcomponent;
	let current;
	aboutcomponent = new _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(aboutcomponent.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true, id: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(aboutcomponent.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "containerfluid");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "id", "about");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 4, 0, 90);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(aboutcomponent, div, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(aboutcomponent.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(aboutcomponent.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(aboutcomponent);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<About> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("About", $$slots, []);
	$$self.$capture_state = () => ({ AboutComponent: _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"] });
	return [];
}

class About extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "About",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (About);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9BYm91dENvbXBvbmVudC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9hYm91dC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs4Q0ErQzJFLEdBQUc7Ozs7Ozs7Ozs7Ozs7OztpREFjSCxHQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7O0tBNUR6RSxHQUFHLEdBQUcsNkJBQTZCO0tBQ25DLE1BQU0sR0FBRyxnQ0FBZ0M7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztBQ0RvQiIsImZpbGUiOiI5M2UwZmIxZGMyYjBmODRkNmZkOC9hYm91dC5hYm91dC5qcyIsInNvdXJjZXNDb250ZW50IjpbIjxzY3JpcHQ+XG4gICAgbGV0IGFsZSA9ICdhc3NldHMvSW1hZ2VzL2Fib3V0L2FsZS5wbmcnO1xuICAgIGxldCBlc3RlZmkgPSAnYXNzZXRzL0ltYWdlcy9hYm91dC9lc3RlZmkucG5nJztcbjwvc2NyaXB0PlxuXG48ZGl2IGNsYXNzPVwiZnVsbGNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJqdW1ib3Ryb25cIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImJhbm5lclwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTYgdGl0bGUgcHQteHMtMTBcIj5cbiAgICAgICAgICAgICAgICAgICAgPGgxIGNsYXNzPVwiIHRleHQtY2VudGVyXCI+XG4gICAgICAgICAgICAgICAgICAgICAgICBOdWVzdHJvXG4gICAgICAgICAgICAgICAgICAgICAgICA8YnIgLz5cbiAgICAgICAgICAgICAgICAgICAgICAgIEluaWNpb1xuICAgICAgICAgICAgICAgICAgICA8L2gxPlxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTZcIj5cbiAgICAgICAgICAgICAgICAgICAgPHAgY2xhc3M9XCJsZWFkIHRleHQtY2VudGVyIGRlc2NcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIE5hY2UgZGUgZG9zIGFtaWdhcyBjb24gZ2FuYXMgZGUgYWNvbXBhw7FhciBhbCBiZWLDqSB5IHN1IGZhbWlsaWEgZHVyYW50ZSBlbFxuICAgICAgICAgICAgICAgICAgICAgICAgbmFjaW1pZW50byB5IGNyZWNpbWllbnRvIHBhcmFcbiAgICAgICAgICAgICAgICAgICAgICAgIDxiPmdlc3RhcjwvYj5cbiAgICAgICAgICAgICAgICAgICAgICAgIGp1bnRvcyBjb25zY2llbmNpYSBzb2JyZVxuICAgICAgICAgICAgICAgICAgICAgICAgPGI+Y3JpYW56YTwvYj5cbiAgICAgICAgICAgICAgICAgICAgICAgIHJlc3BldHVvc2EuXG4gICAgICAgICAgICAgICAgICAgICAgICA8YnIgLz5cbiAgICAgICAgICAgICAgICAgICAgICAgIFNlbnRpbW9zIHkgZWxlZ2ltb3MgaGFjZXJsbyBicmluZGFuZG8gYXNlc29yYW1pZW50byBzb2JyZVxuICAgICAgICAgICAgICAgICAgICAgICAgPGI+cG9ydGVvPC9iPlxuICAgICAgICAgICAgICAgICAgICAgICAgZXJnb27Ds21pY28gKHRhbnRvIHBhcnRpY3VsYXJlcyBjb21vIGdydXBhbGVzKSB5IGEgdHJhdsOpcyBkZSBsYSB2ZW50YSBkZVxuICAgICAgICAgICAgICAgICAgICAgICAgPGI+cG9ydGFiZWJlcyB5IGFydGljdWxvczwvYj5cbiAgICAgICAgICAgICAgICAgICAgICAgIHJlc3BldHVvc29zIHBhcmEgbG9zIG5pw7Fvcy5cbiAgICAgICAgICAgICAgICAgICAgPC9wPlxuICAgICAgICAgICAgICAgIDwvZGl2PlxuXG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgIDxzcGFuIGNsYXNzPVwiYXJyb3cgYm91bmNlIGFsaWduLXRleHQtYm90dG9tIGQtbm9uZSBkLW1kLWlubGluZSB0ZXh0LWNlbnRlclwiPlxuICAgICAgICAgICAgICAgIDxpIGNsYXNzPVwiZmFzIGZhLWFuZ2xlLWRvdWJsZS1kb3duIGFsaWduLXRleHQtYm90dG9tXCI+PC9pPlxuICAgICAgICAgICAgPC9zcGFuPlxuICAgICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3cgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2xcIj5cbiAgICAgICAgICAgICAgICA8aDEgY2xhc3M9XCJub3NvdHJhcy10aXRsZVwiPk5vc290cmFzPC9oMT5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvdyBub3NvdHJhcyB0ZXh0LWNlbnRlclwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNlwiPlxuICAgICAgICAgICAgICAgIDxpbWcgYWx0PVwiLi4uXCIgY2xhc3M9XCJhbGlnbi1zZWxmLWNlbnRlciBtci0zIGFsZWltZ1wiIHNyYz1cInthbGV9XCIgLz5cbiAgICAgICAgICAgICAgICA8ZGl2IGNsYXNzPVwibWVkaWEgcm93XCI+XG4gICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTJcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYS1ib2R5XCI+XG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPGg1IGNsYXNzPVwibXQtMCBtYi0xXCI+QWxlPC9oNT5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8cD5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgRXN0dWRpYW50ZSBhdmFuemFkYSBkZSBBZG1pbmlzdHJhY2nDs24gZGUgRW1wcmVzYXMgeSB0cmFiYWphIGNvbW9cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgYWRtaW5pc3RyYXRpdmEgY29udGFibGUuXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9wPlxuICAgICAgICAgICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC02XCI+XG4gICAgICAgICAgICAgICAgPGltZyBhbHQ9XCIuLi5cIiBjbGFzcz1cImFsaWduLXNlbGYtY2VudGVyIG1yLTMgYWxlaW1nXCIgc3JjPVwie2VzdGVmaX1cIiAvPlxuICAgICAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYSByb3dcIj5cbiAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMlwiPlxuICAgICAgICAgICAgICAgICAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhLWJvZHlcIj5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8aDUgY2xhc3M9XCJtdC0wIG1iLTFcIj5Fc3RlZmk8L2g1PlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICBPcmdhbml6YWRvcmEgZGUgZXZlbnRvcy8gRG91bGEgLyBDb25zdWx0b3JhIGVuIHBvcnRlbyBkZSBDcmlhbnphIGVuXG4gICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIEJyYXpvcy5cbiAgICAgICAgICAgICAgICAgICAgICAgICAgICA8L3A+XG4gICAgICAgICAgICAgICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgICA8L2Rpdj5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG5cbiAgICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGVzcGFjaW9cIj5cbiAgICAgICAgPGhyIC8+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxoMT5OdWVzdHJvIEVzcGFjaW88L2gxPlxuICAgICAgICA8L2Rpdj5cbiAgICAgICAgPGRpdiBjbGFzcz1cInJvdyB2aXNpdGFcIj5cbiAgICAgICAgICAgIDxoNT5QYWN0YW1vcyB0dSB2aXNpdGEgY29uIHByZXZpbyBhdmlzbzwvaDU+XG5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIGNsYXNzPVwiYnRuIGJ0bi1kYW5nZXJcIj5cbiAgICAgICAgICAgIDxhXG4gICAgICAgICAgICAgICAgdGFyZ2V0PVwiX2JsYW5rXCJcbiAgICAgICAgICAgICAgICBocmVmPVwiaHR0cHM6Ly9hcGkud2hhdHNhcHAuY29tL3NlbmQ/cGhvbmU9NTQ5MzYyNDI2MDgzOSZ0ZXh0PU1lJTIwaW50ZXJlc2ElMjBwYWN0YXIlMjB1bmElMjBjaXRhXCJcbiAgICAgICAgICAgID5cbiAgICAgICAgICAgICAgICBQYWN0YXIgdmlzaXRhXG4gICAgICAgICAgICA8L2E+XG4gICAgICAgIDwvYnV0dG9uPlxuXG4gICAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgICAgIDxpZnJhbWVcbiAgICAgICAgICAgICAgICB0aXRsZT1cIm1hcGFcIlxuICAgICAgICAgICAgICAgIGFsbG93RnVsbFNjcmVlbj1cIlwiXG4gICAgICAgICAgICAgICAgY2xhc3M9XCJtYXBcIlxuICAgICAgICAgICAgICAgIGZyYW1lQm9yZGVyPVwiMFwiXG4gICAgICAgICAgICAgICAgaGVpZ2h0PVwiNjAwXCJcbiAgICAgICAgICAgICAgICBzcmM9XCJodHRwczovL3d3dy5nb29nbGUuY29tL21hcHMvZW1iZWQ/cGI9ITFtMTghMW0xMiExbTMhMWQzNTQwLjQ3MDk0OTgwMzc5NiEyZC01OS4wMDQ3NjA4ODQ4NDg5NSEzZC0yNy40NTQ1OTM5ODI4OTcyMzchMm0zITFmMCEyZjAhM2YwITNtMiExaTEwMjQhMmk3NjghNGYxMy4xITNtMyExbTIhMXMweDk0NDUwYzg2NDc0ZTBjMjclM0EweDY2YTJiOWJjZjZiZmY1MjEhMnNDYW5nYWxsbysxMTM3JTJDK0gzNTA4K1Jlc2lzdGVuY2lhJTJDK0NoYWNvITVlMCEzbTIhMXNlcy00MTkhMnNhciE0djE1NTYxOTgzMTk0MTAhNW0yITFzZXMtNDE5ITJzYXJcIlxuICAgICAgICAgICAgICAgIHN0eWxlcz1cImJvcmRlcjowXCJcbiAgICAgICAgICAgICAgICB3aWR0aD1cIjgwMFwiXG4gICAgICAgICAgICA+PC9pZnJhbWU+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgICAgICA8aHIgLz5cbiAgICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG48L2Rpdj5cblxuPHN0eWxlPlxuICAgIC5idG4tZGFuZ2VyIHtcbiAgICAgICAgbWFyZ2luLWJvdHRvbTogMTBweDtcbiAgICB9XG4gICAgYSB7XG4gICAgICAgIHRleHQtZGVjb3JhdGlvbjogaW5oZXJpdDtcbiAgICAgICAgY29sb3I6IGluaGVyaXQ7XG4gICAgICAgIGN1cnNvcjogcG9pbnRlcjtcbiAgICB9XG4gICAgLmJvdW5jZSB7XG4gICAgICAgIGFuaW1hdGlvbjogYm91bmNlIDJzIGluZmluaXRlO1xuICAgIH1cblxuICAgIEBrZXlmcmFtZXMgYm91bmNlIHtcbiAgICAgICAgMCUsXG4gICAgICAgIDIwJSxcbiAgICAgICAgNTAlLFxuICAgICAgICA4MCUsXG4gICAgICAgIDEwMCUge1xuICAgICAgICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApO1xuICAgICAgICB9XG4gICAgICAgIDQwJSB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTMwcHgpO1xuICAgICAgICB9XG4gICAgICAgIDYwJSB7XG4gICAgICAgICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTE1cHgpO1xuICAgICAgICB9XG4gICAgfVxuXG4gICAgLmZhLWFuZ2xlLWRvdWJsZS1kb3duIHtcbiAgICAgICAgZm9udC1zaXplOiA3MHB4ICFpbXBvcnRhbnQ7XG4gICAgfVxuICAgIEBtZWRpYSAobWluLXdpZHRoOiA3NjhweCkge1xuICAgICAgICAuanVtYm90cm9uIHtcbiAgICAgICAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybCgnYXNzZXRzL0ltYWdlcy9hYm91dC9lc3BhY2lvLmpwZycpO1xuICAgICAgICAgICAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgICAgICAgICAgIGJhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7XG4gICAgICAgICAgICBjb2xvcjogd2hpdGU7XG4gICAgICAgICAgICBoZWlnaHQ6IDkwdmg7XG4gICAgICAgICAgICBtYXJnaW46IDAgIWltcG9ydGFudDtcbiAgICAgICAgICAgIG92ZXJmbG93OiBoaWRkZW47XG4gICAgICAgICAgICBwYWRkaW5nLXRvcDogMTVweCAhaW1wb3J0YW50O1xuICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDAgIWltcG9ydGFudDtcbiAgICAgICAgICAgIGJvcmRlci1yYWRpdXM6IDAgIWltcG9ydGFudDtcbiAgICAgICAgfVxuICAgICAgICAuYXJyb3cge1xuICAgICAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgICAgICAgbWFyZ2luOiA4JSAwO1xuICAgICAgICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgICAgICAgdG9wOiA4MHZoO1xuICAgICAgICAgICAgbGVmdDogNDh2dztcbiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgICAgICAgIHBhZGRpbmc6IDA7XG4gICAgICAgICAgICBtYXJnaW46IDA7XG4gICAgICAgICAgICB6LWluZGV4OiA0O1xuICAgICAgICAgICAgZGlzcGxheTogaW5saW5lO1xuICAgICAgICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgICAgICAgb3BhY2l0eTogMC42O1xuICAgICAgICB9XG5cbiAgICAgICAgLnRpdGxlIGgxIHtcbiAgICAgICAgICAgIHBhZGRpbmctdG9wOiAyOXZoO1xuICAgICAgICAgICAgZm9udC1zaXplOiA1LjVyZW07XG4gICAgICAgIH1cbiAgICAgICAgLmxlYWQge1xuICAgICAgICAgICAgZm9udC1zaXplOiAxLjd2dztcbiAgICAgICAgICAgIHBhZGRpbmctYm90dG9tOiAyMHB4O1xuICAgICAgICAgICAgcGFkZGluZy10b3A6IDMwdmg7XG4gICAgICAgIH1cblxuICAgICAgICAuYWxlaW1nIHtcbiAgICAgICAgICAgIG1heC13aWR0aDogMTJ2dztcbiAgICAgICAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICAgICAgfVxuICAgIH1cblxuICAgIC5ub3NvdHJhcy10aXRsZSB7XG4gICAgICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gICAgfVxuXG4gICAgQG1lZGlhIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gICAgICAgIC5qdW1ib3Ryb24ge1xuICAgICAgICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKCdhc3NldHMvSW1hZ2VzL2Fib3V0L2VzcGFjaW8uanBnJyk7XG4gICAgICAgICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgICAgICAgIGhlaWdodDogMTgwdnc7XG4gICAgICAgICAgICBtYXJnaW46IDAgIWltcG9ydGFudDtcbiAgICAgICAgICAgIG92ZXJmbG93OiBoaWRkZW47XG4gICAgICAgICAgICBwYWRkaW5nLXRvcDogMTVweCAhaW1wb3J0YW50O1xuICAgICAgICAgICAgcGFkZGluZy1ib3R0b206IDAgIWltcG9ydGFudDtcbiAgICAgICAgICAgIGJvcmRlci1yYWRpdXM6IDAgIWltcG9ydGFudDtcbiAgICAgICAgfVxuXG4gICAgICAgIC50aXRsZSBoMSB7XG4gICAgICAgICAgICBwYWRkaW5nLXRvcDogMDtcbiAgICAgICAgICAgIGZvbnQtc2l6ZTogNzBweCAhaW1wb3J0YW50O1xuICAgICAgICB9XG4gICAgICAgIC5sZWFkIHtcbiAgICAgICAgICAgIGZvbnQtc2l6ZTogMThweDtcbiAgICAgICAgICAgIHBhZGRpbmctYm90dG9tOiAyMHB4O1xuICAgICAgICAgICAgLyogcGFkZGluZy10b3A6IDsgKi9cbiAgICAgICAgICAgIG1hcmdpbi1ib3R0b206IDI1cHg7XG4gICAgICAgIH1cblxuICAgICAgICAuYWxlaW1nIHtcbiAgICAgICAgICAgIG1heC13aWR0aDogMTAwcHg7XG4gICAgICAgICAgICBwYWRkaW5nLWxlZnQ6IDIwcHg7XG4gICAgICAgIH1cbiAgICB9XG5cbiAgICAuZmFzIHtcbiAgICAgICAgZm9udC1zaXplOiA3MHB4O1xuICAgICAgICBjb2xvcjogd2hpdGUgIWltcG9ydGFudDtcbiAgICB9XG5cbiAgICAuYWxpZ24tdGV4dC1ib3R0b20ge1xuICAgICAgICB2ZXJ0aWNhbC1hbGlnbjogdGV4dC1ib3R0b20gIWltcG9ydGFudDtcbiAgICB9XG5cbiAgICAubWVkaWEge1xuICAgICAgICBkaXNwbGF5OiAtbXMtZmxleGJveDtcbiAgICAgICAgcGFkZGluZzogNXB4O1xuICAgICAgICBkaXNwbGF5OiBmbGV4O1xuICAgICAgICAtbXMtZmxleC1hbGlnbjogc3RhcnQ7XG4gICAgICAgIGFsaWduLWl0ZW1zOiBmbGV4LXN0YXJ0O1xuICAgIH1cbiAgICAubm9zb3RyYXMge1xuICAgICAgICBwYWRkaW5nOiAxNXB4O1xuICAgICAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICAgIH1cblxuICAgIC5lc3BhY2lvIHtcbiAgICAgICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgICAgICAgcGFkZGluZy1ib3R0b206IDE1cHg7XG4gICAgfVxuICAgIC52aXNpdGEge1xuICAgICAgICBvcGFjaXR5OiAwLjU7XG4gICAgICAgIHBhZGRpbmctYm90dG9tOiAzcHg7XG4gICAgfVxuXG4gICAgLm1hcCB7XG4gICAgICAgIHdpZHRoOiAxMDB2dztcbiAgICAgICAgaGVpZ2h0OiA0MHZoO1xuICAgIH1cbjwvc3R5bGU+XG4iLCI8c2NyaXB0PlxuICAgIGltcG9ydCBBYm91dENvbXBvbmVudCBmcm9tICcuLi9jb21wb25lbnRzL0Fib3V0Q29tcG9uZW50LnN2ZWx0ZSc7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cImNvbnRhaW5lcmZsdWlkXCIgaWQ9XCJhYm91dFwiPlxuICAgIDxBYm91dENvbXBvbmVudCAvPlxuPC9kaXY+XG5cbjxzdHlsZT5cblxuPC9zdHlsZT5cbiJdLCJzb3VyY2VSb290IjoiIn0=