(window["webpackJsonp"] = window["webpackJsonp"] || []).push([["about"],{

/***/ "./src/components/AboutComponent.svelte":
/*!**********************************************!*\
  !*** ./src/components/AboutComponent.svelte ***!
  \**********************************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* src/components/AboutComponent.svelte generated by Svelte v3.24.0 */


const file = "src/components/AboutComponent.svelte";

function add_css() {
	var style = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("style");
	style.id = "svelte-sb05x7-style";
	style.textContent = ".btn-danger.svelte-sb05x7.svelte-sb05x7{margin-bottom:10px}a.svelte-sb05x7.svelte-sb05x7{text-decoration:inherit;color:inherit;cursor:pointer}.bounce.svelte-sb05x7.svelte-sb05x7{animation:svelte-sb05x7-bounce 2s infinite}@keyframes svelte-sb05x7-bounce{0%,20%,50%,80%,100%{transform:translateY(0)}40%{transform:translateY(-30px)}60%{transform:translateY(-15px)}}.fa-angle-double-down.svelte-sb05x7.svelte-sb05x7{font-size:70px !important}@media(min-width: 768px){.jumbotron.svelte-sb05x7.svelte-sb05x7{background-image:url(\"assets/Images/about/esp.jpg\");background-size:cover;background-repeat:no-repeat;color:white;height:90vh;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.arrow.svelte-sb05x7.svelte-sb05x7{text-align:center;margin:8% 0;position:absolute;top:80vh;left:48vw;color:white;padding:0;margin:0;z-index:4;display:inline;text-align:center;opacity:0.6}.title.svelte-sb05x7 h1.svelte-sb05x7{padding-top:29vh;font-size:5.5rem}.lead.svelte-sb05x7.svelte-sb05x7{font-size:1.7vw;padding-bottom:20px;padding-top:30vh}.aleimg.svelte-sb05x7.svelte-sb05x7{max-width:12vw;padding-left:20px}}.nosotras-title.svelte-sb05x7.svelte-sb05x7{padding:15px;color:rgb(190, 86, 89) !important}@media(max-width: 768px){.jumbotron.svelte-sb05x7.svelte-sb05x7{background-image:url(\"assets/Images/about/espacio.jpg\");background-size:cover;background-repeat:no-repeat;color:white;height:180vw;margin:0 !important;overflow:hidden;padding-top:15px !important;padding-bottom:0 !important;border-radius:0 !important}.title.svelte-sb05x7 h1.svelte-sb05x7{padding-top:0;font-size:60px !important}.lead.svelte-sb05x7.svelte-sb05x7{font-size:18px;padding-bottom:20px;margin-bottom:25px}.aleimg.svelte-sb05x7.svelte-sb05x7{max-width:100px;padding-left:20px}}.fas.svelte-sb05x7.svelte-sb05x7{font-size:70px;color:white !important}.align-text-bottom.svelte-sb05x7.svelte-sb05x7{vertical-align:text-bottom !important}.media.svelte-sb05x7.svelte-sb05x7{display:-ms-flexbox;padding:5px;display:flex;-ms-flex-align:start;align-items:flex-start}.nosotras.svelte-sb05x7.svelte-sb05x7{padding:15px;color:rgb(190, 86, 89) !important}.espacio.svelte-sb05x7.svelte-sb05x7{color:rgb(190, 86, 89) !important;padding-bottom:15px}.visita.svelte-sb05x7.svelte-sb05x7{opacity:0.5;padding-bottom:3px}.map.svelte-sb05x7.svelte-sb05x7{width:100vw;height:40vh}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiQWJvdXRDb21wb25lbnQuc3ZlbHRlIiwic291cmNlcyI6WyJBYm91dENvbXBvbmVudC5zdmVsdGUiXSwic291cmNlc0NvbnRlbnQiOlsiPHNjcmlwdD5cbiAgbGV0IGFsZSA9IFwiYXNzZXRzL0ltYWdlcy9hYm91dC9hbGUucG5nXCI7XG4gIGxldCBlc3RlZmkgPSBcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXN0ZWZpLnBuZ1wiO1xuPC9zY3JpcHQ+XG5cbjxzdHlsZT5cbiAgLmJ0bi1kYW5nZXIge1xuICAgIG1hcmdpbi1ib3R0b206IDEwcHg7XG4gIH1cbiAgYSB7XG4gICAgdGV4dC1kZWNvcmF0aW9uOiBpbmhlcml0O1xuICAgIGNvbG9yOiBpbmhlcml0O1xuICAgIGN1cnNvcjogcG9pbnRlcjtcbiAgfVxuICAuYm91bmNlIHtcbiAgICBhbmltYXRpb246IGJvdW5jZSAycyBpbmZpbml0ZTtcbiAgfVxuXG4gIEBrZXlmcmFtZXMgYm91bmNlIHtcbiAgICAwJSxcbiAgICAyMCUsXG4gICAgNTAlLFxuICAgIDgwJSxcbiAgICAxMDAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgwKTtcbiAgICB9XG4gICAgNDAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMzBweCk7XG4gICAgfVxuICAgIDYwJSB7XG4gICAgICB0cmFuc2Zvcm06IHRyYW5zbGF0ZVkoLTE1cHgpO1xuICAgIH1cbiAgfVxuXG4gIC5mYS1hbmdsZS1kb3VibGUtZG93biB7XG4gICAgZm9udC1zaXplOiA3MHB4ICFpbXBvcnRhbnQ7XG4gIH1cbiAgQG1lZGlhIChtaW4td2lkdGg6IDc2OHB4KSB7XG4gICAgLmp1bWJvdHJvbiB7XG4gICAgICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoXCJhc3NldHMvSW1hZ2VzL2Fib3V0L2VzcC5qcGdcIik7XG4gICAgICBiYWNrZ3JvdW5kLXNpemU6IGNvdmVyO1xuICAgICAgYmFja2dyb3VuZC1yZXBlYXQ6IG5vLXJlcGVhdDtcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIGhlaWdodDogOTB2aDtcbiAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgIH1cbiAgICAuYXJyb3cge1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgbWFyZ2luOiA4JSAwO1xuICAgICAgcG9zaXRpb246IGFic29sdXRlO1xuICAgICAgdG9wOiA4MHZoO1xuICAgICAgbGVmdDogNDh2dztcbiAgICAgIGNvbG9yOiB3aGl0ZTtcbiAgICAgIHBhZGRpbmc6IDA7XG4gICAgICBtYXJnaW46IDA7XG4gICAgICB6LWluZGV4OiA0O1xuICAgICAgZGlzcGxheTogaW5saW5lO1xuICAgICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgICAgb3BhY2l0eTogMC42O1xuICAgIH1cblxuICAgIC50aXRsZSBoMSB7XG4gICAgICBwYWRkaW5nLXRvcDogMjl2aDtcbiAgICAgIGZvbnQtc2l6ZTogNS41cmVtO1xuICAgIH1cbiAgICAubGVhZCB7XG4gICAgICBmb250LXNpemU6IDEuN3Z3O1xuICAgICAgcGFkZGluZy1ib3R0b206IDIwcHg7XG4gICAgICBwYWRkaW5nLXRvcDogMzB2aDtcbiAgICB9XG5cbiAgICAuYWxlaW1nIHtcbiAgICAgIG1heC13aWR0aDogMTJ2dztcbiAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICB9XG4gIH1cblxuICAubm9zb3RyYXMtdGl0bGUge1xuICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgfVxuXG4gIEBtZWRpYSAobWF4LXdpZHRoOiA3NjhweCkge1xuICAgIC5qdW1ib3Ryb24ge1xuICAgICAgYmFja2dyb3VuZC1pbWFnZTogdXJsKFwiYXNzZXRzL0ltYWdlcy9hYm91dC9lc3BhY2lvLmpwZ1wiKTtcbiAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gICAgICBiYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgaGVpZ2h0OiAxODB2dztcbiAgICAgIG1hcmdpbjogMCAhaW1wb3J0YW50O1xuICAgICAgb3ZlcmZsb3c6IGhpZGRlbjtcbiAgICAgIHBhZGRpbmctdG9wOiAxNXB4ICFpbXBvcnRhbnQ7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMCAhaW1wb3J0YW50O1xuICAgICAgYm9yZGVyLXJhZGl1czogMCAhaW1wb3J0YW50O1xuICAgIH1cblxuICAgIC50aXRsZSBoMSB7XG4gICAgICBwYWRkaW5nLXRvcDogMDtcbiAgICAgIGZvbnQtc2l6ZTogNjBweCAhaW1wb3J0YW50O1xuICAgIH1cbiAgICAubGVhZCB7XG4gICAgICBmb250LXNpemU6IDE4cHg7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMjBweDtcbiAgICAgIC8qIHBhZGRpbmctdG9wOiA7ICovXG4gICAgICBtYXJnaW4tYm90dG9tOiAyNXB4O1xuICAgIH1cblxuICAgIC5hbGVpbWcge1xuICAgICAgbWF4LXdpZHRoOiAxMDBweDtcbiAgICAgIHBhZGRpbmctbGVmdDogMjBweDtcbiAgICB9XG4gIH1cblxuICAuZmFzIHtcbiAgICBmb250LXNpemU6IDcwcHg7XG4gICAgY29sb3I6IHdoaXRlICFpbXBvcnRhbnQ7XG4gIH1cblxuICAuYWxpZ24tdGV4dC1ib3R0b20ge1xuICAgIHZlcnRpY2FsLWFsaWduOiB0ZXh0LWJvdHRvbSAhaW1wb3J0YW50O1xuICB9XG5cbiAgLm1lZGlhIHtcbiAgICBkaXNwbGF5OiAtbXMtZmxleGJveDtcbiAgICBwYWRkaW5nOiA1cHg7XG4gICAgZGlzcGxheTogZmxleDtcbiAgICAtbXMtZmxleC1hbGlnbjogc3RhcnQ7XG4gICAgYWxpZ24taXRlbXM6IGZsZXgtc3RhcnQ7XG4gIH1cbiAgLm5vc290cmFzIHtcbiAgICBwYWRkaW5nOiAxNXB4O1xuICAgIGNvbG9yOiByZ2IoMTkwLCA4NiwgODkpICFpbXBvcnRhbnQ7XG4gIH1cblxuICAuZXNwYWNpbyB7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgICBwYWRkaW5nLWJvdHRvbTogMTVweDtcbiAgfVxuICAudmlzaXRhIHtcbiAgICBvcGFjaXR5OiAwLjU7XG4gICAgcGFkZGluZy1ib3R0b206IDNweDtcbiAgfVxuXG4gIC5tYXAge1xuICAgIHdpZHRoOiAxMDB2dztcbiAgICBoZWlnaHQ6IDQwdmg7XG4gIH1cbjwvc3R5bGU+XG5cbjxkaXYgY2xhc3M9XCJmdWxsY29udGFpbmVyXCI+XG4gIDxkaXYgY2xhc3M9XCJqdW1ib3Ryb25cIj5cbiAgICA8ZGl2IGNsYXNzPVwiYmFubmVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTYgdGl0bGUgcHQteHMtMTBcIj5cbiAgICAgICAgICA8aDEgY2xhc3M9XCIgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgICAgIMK/UXXDqSBlc1xuICAgICAgICAgICAgPGJyIC8+XG4gICAgICAgICAgICBaYXJpZ8O8ZXlhP1xuICAgICAgICAgIDwvaDE+XG4gICAgICAgIDwvZGl2PlxuICAgICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC02XCI+XG4gICAgICAgICAgPHAgY2xhc3M9XCJsZWFkIHRleHQtY2VudGVyIGRlc2NcIj5cbiAgICAgICAgICAgIFVuIGVzcGFjaW8gZGVzdGluYWRvIGEgbGFzIGZhbWlsaWFzIGRvbmRlIHBvZHLDoW4gYXNlc29yYXJzZSBlblxuICAgICAgICAgICAgcG9ydGVvIGVyZ29ub21pY28sIGNvbm9jZXIgZGlmZXJlbnRlcyBtb2RlbG9zIGRlIHBvcnRhYmViw6lzIHlcbiAgICAgICAgICAgIGFkcXVpcmlyIGVsIHF1ZSBzZSBhZGFwdGUgYSBzdXMgbmVjZXNpZGFkZXMuIFByb211ZXZlIGVsIHBvcnRlbyB5IGxhXG4gICAgICAgICAgICBjcmlhbnphIHJlc3BldHVvc2EgYSB0cmF2ZXMgZGUgYXNlc29yYW1pZW50b3MgZ3J1cGFsZXMsIHJvbmRhcyxcbiAgICAgICAgICAgIHRhbGxlcmVzIHkgY2xhc2VzIGRlIGJhaWxlcyBwb3J0ZWFuZG8uXG4gICAgICAgICAgPC9wPlxuICAgICAgICA8L2Rpdj5cblxuICAgICAgPC9kaXY+XG4gICAgICA8c3BhblxuICAgICAgICBjbGFzcz1cImFycm93IGJvdW5jZSBhbGlnbi10ZXh0LWJvdHRvbSBkLW5vbmUgZC1tZC1pbmxpbmUgdGV4dC1jZW50ZXJcIj5cbiAgICAgICAgPGkgY2xhc3M9XCJmYXMgZmEtYW5nbGUtZG91YmxlLWRvd24gYWxpZ24tdGV4dC1ib3R0b21cIiAvPlxuICAgICAgPC9zcGFuPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbiAgPGRpdiBjbGFzcz1cImNvbnRhaW5lclwiPlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgdGV4dC1jZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjb2xcIj5cbiAgICAgICAgPGgxIGNsYXNzPVwibm9zb3RyYXMtdGl0bGVcIj5Ob3NvdHJhczwvaDE+XG4gICAgICA8L2Rpdj5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IG5vc290cmFzIHRleHQtY2VudGVyIGFsaWduLXNlbGYtY2VudGVyXCI+XG4gICAgICA8ZGl2IGNsYXNzPVwiY29sLTEyIGNvbC1tZC0xMlwiPlxuICAgICAgICA8aW1nIGFsdD1cIi4uLlwiIGNsYXNzPVwiYWxpZ24tc2VsZi1jZW50ZXIgbXItMyBhbGVpbWdcIiBzcmM9e2VzdGVmaX0gLz5cbiAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhIHJvd1wiPlxuICAgICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTJcIj5cbiAgICAgICAgICAgIDxkaXYgY2xhc3M9XCJtZWRpYS1ib2R5XCI+XG4gICAgICAgICAgICAgIDxoNSBjbGFzcz1cIm10LTAgbWItMVwiPkVzdGVmaTwvaDU+XG4gICAgICAgICAgICAgIDxwPlxuICAgICAgICAgICAgICAgIE9yZ2FuaXphZG9yYSBkZSBldmVudG9zLyBEb3VsYSAvIENvbnN1bHRvcmEgZW4gcG9ydGVvIGRlIENyaWFuemFcbiAgICAgICAgICAgICAgICBlbiBCcmF6b3MuXG4gICAgICAgICAgICAgIDwvcD5cbiAgICAgICAgICAgIDwvZGl2PlxuICAgICAgICAgIDwvZGl2PlxuICAgICAgICA8L2Rpdj5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cblxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyIGVzcGFjaW9cIj5cbiAgICA8aHIgLz5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8aDE+TnVlc3RybyBFc3BhY2lvPC9oMT5cbiAgICA8L2Rpdj5cbiAgICA8ZGl2IGNsYXNzPVwicm93IHZpc2l0YVwiPlxuICAgICAgPGg1PlBhY3RhbW9zIHR1IHZpc2l0YSBjb24gcHJldmlvIGF2aXNvPC9oNT5cblxuICAgIDwvZGl2PlxuICAgIDxidXR0b24gdHlwZT1cImJ1dHRvblwiIGNsYXNzPVwiYnRuIGJ0bi1kYW5nZXJcIj5cbiAgICAgIDxhXG4gICAgICAgIHRhcmdldD1cIl9ibGFua1wiXG4gICAgICAgIGhyZWY9XCJodHRwczovL2FwaS53aGF0c2FwcC5jb20vc2VuZD9waG9uZT01NDkzNjI0MjYwODM5JnRleHQ9TWUlMjBpbnRlcmVzYSUyMHBhY3RhciUyMHVuYSUyMGNpdGFcIj5cbiAgICAgICAgUGFjdGFyIHZpc2l0YVxuICAgICAgPC9hPlxuICAgIDwvYnV0dG9uPlxuXG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGlmcmFtZVxuICAgICAgICB0aXRsZT1cIm1hcGFcIlxuICAgICAgICBhbGxvd0Z1bGxTY3JlZW49XCJcIlxuICAgICAgICBjbGFzcz1cIm1hcFwiXG4gICAgICAgIGZyYW1lQm9yZGVyPVwiMFwiXG4gICAgICAgIGhlaWdodD1cIjYwMFwiXG4gICAgICAgIHNyYz1cImh0dHBzOi8vd3d3Lmdvb2dsZS5jb20vbWFwcy9lbWJlZD9wYj0hMW0xOCExbTEyITFtMyExZDM1NDAuNDcwOTQ5ODAzNzk2ITJkLTU5LjAwNDc2MDg4NDg0ODk1ITNkLTI3LjQ1NDU5Mzk4Mjg5NzIzNyEybTMhMWYwITJmMCEzZjAhM20yITFpMTAyNCEyaTc2OCE0ZjEzLjEhM20zITFtMiExczB4OTQ0NTBjODY0NzRlMGMyNyUzQTB4NjZhMmI5YmNmNmJmZjUyMSEyc0NhbmdhbGxvKzExMzclMkMrSDM1MDgrUmVzaXN0ZW5jaWElMkMrQ2hhY28hNWUwITNtMiExc2VzLTQxOSEyc2FyITR2MTU1NjE5ODMxOTQxMCE1bTIhMXNlcy00MTkhMnNhclwiXG4gICAgICAgIHN0eWxlcz1cImJvcmRlcjowXCJcbiAgICAgICAgd2lkdGg9XCI4MDBcIiAvPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgIDxociAvPlxuICAgIDwvZGl2PlxuICA8L2Rpdj5cbjwvZGl2PlxuIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQU1FLFdBQVcsNEJBQUMsQ0FBQyxBQUNYLGFBQWEsQ0FBRSxJQUFJLEFBQ3JCLENBQUMsQUFDRCxDQUFDLDRCQUFDLENBQUMsQUFDRCxlQUFlLENBQUUsT0FBTyxDQUN4QixLQUFLLENBQUUsT0FBTyxDQUNkLE1BQU0sQ0FBRSxPQUFPLEFBQ2pCLENBQUMsQUFDRCxPQUFPLDRCQUFDLENBQUMsQUFDUCxTQUFTLENBQUUsb0JBQU0sQ0FBQyxFQUFFLENBQUMsUUFBUSxBQUMvQixDQUFDLEFBRUQsV0FBVyxvQkFBTyxDQUFDLEFBQ2pCLEVBQUUsQ0FDRixHQUFHLENBQ0gsR0FBRyxDQUNILEdBQUcsQ0FDSCxJQUFJLEFBQUMsQ0FBQyxBQUNKLFNBQVMsQ0FBRSxXQUFXLENBQUMsQ0FBQyxBQUMxQixDQUFDLEFBQ0QsR0FBRyxBQUFDLENBQUMsQUFDSCxTQUFTLENBQUUsV0FBVyxLQUFLLENBQUMsQUFDOUIsQ0FBQyxBQUNELEdBQUcsQUFBQyxDQUFDLEFBQ0gsU0FBUyxDQUFFLFdBQVcsS0FBSyxDQUFDLEFBQzlCLENBQUMsQUFDSCxDQUFDLEFBRUQscUJBQXFCLDRCQUFDLENBQUMsQUFDckIsU0FBUyxDQUFFLElBQUksQ0FBQyxVQUFVLEFBQzVCLENBQUMsQUFDRCxNQUFNLEFBQUMsWUFBWSxLQUFLLENBQUMsQUFBQyxDQUFDLEFBQ3pCLFVBQVUsNEJBQUMsQ0FBQyxBQUNWLGdCQUFnQixDQUFFLElBQUksNkJBQTZCLENBQUMsQ0FDcEQsZUFBZSxDQUFFLEtBQUssQ0FDdEIsaUJBQWlCLENBQUUsU0FBUyxDQUM1QixLQUFLLENBQUUsS0FBSyxDQUNaLE1BQU0sQ0FBRSxJQUFJLENBQ1osTUFBTSxDQUFFLENBQUMsQ0FBQyxVQUFVLENBQ3BCLFFBQVEsQ0FBRSxNQUFNLENBQ2hCLFdBQVcsQ0FBRSxJQUFJLENBQUMsVUFBVSxDQUM1QixjQUFjLENBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDNUIsYUFBYSxDQUFFLENBQUMsQ0FBQyxVQUFVLEFBQzdCLENBQUMsQUFDRCxNQUFNLDRCQUFDLENBQUMsQUFDTixVQUFVLENBQUUsTUFBTSxDQUNsQixNQUFNLENBQUUsRUFBRSxDQUFDLENBQUMsQ0FDWixRQUFRLENBQUUsUUFBUSxDQUNsQixHQUFHLENBQUUsSUFBSSxDQUNULElBQUksQ0FBRSxJQUFJLENBQ1YsS0FBSyxDQUFFLEtBQUssQ0FDWixPQUFPLENBQUUsQ0FBQyxDQUNWLE1BQU0sQ0FBRSxDQUFDLENBQ1QsT0FBTyxDQUFFLENBQUMsQ0FDVixPQUFPLENBQUUsTUFBTSxDQUNmLFVBQVUsQ0FBRSxNQUFNLENBQ2xCLE9BQU8sQ0FBRSxHQUFHLEFBQ2QsQ0FBQyxBQUVELG9CQUFNLENBQUMsRUFBRSxjQUFDLENBQUMsQUFDVCxXQUFXLENBQUUsSUFBSSxDQUNqQixTQUFTLENBQUUsTUFBTSxBQUNuQixDQUFDLEFBQ0QsS0FBSyw0QkFBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLEtBQUssQ0FDaEIsY0FBYyxDQUFFLElBQUksQ0FDcEIsV0FBVyxDQUFFLElBQUksQUFDbkIsQ0FBQyxBQUVELE9BQU8sNEJBQUMsQ0FBQyxBQUNQLFNBQVMsQ0FBRSxJQUFJLENBQ2YsWUFBWSxDQUFFLElBQUksQUFDcEIsQ0FBQyxBQUNILENBQUMsQUFFRCxlQUFlLDRCQUFDLENBQUMsQUFDZixPQUFPLENBQUUsSUFBSSxDQUNiLEtBQUssQ0FBRSxJQUFJLEdBQUcsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLEVBQUUsQ0FBQyxDQUFDLFVBQVUsQUFDcEMsQ0FBQyxBQUVELE1BQU0sQUFBQyxZQUFZLEtBQUssQ0FBQyxBQUFDLENBQUMsQUFDekIsVUFBVSw0QkFBQyxDQUFDLEFBQ1YsZ0JBQWdCLENBQUUsSUFBSSxpQ0FBaUMsQ0FBQyxDQUN4RCxlQUFlLENBQUUsS0FBSyxDQUN0QixpQkFBaUIsQ0FBRSxTQUFTLENBQzVCLEtBQUssQ0FBRSxLQUFLLENBQ1osTUFBTSxDQUFFLEtBQUssQ0FDYixNQUFNLENBQUUsQ0FBQyxDQUFDLFVBQVUsQ0FDcEIsUUFBUSxDQUFFLE1BQU0sQ0FDaEIsV0FBVyxDQUFFLElBQUksQ0FBQyxVQUFVLENBQzVCLGNBQWMsQ0FBRSxDQUFDLENBQUMsVUFBVSxDQUM1QixhQUFhLENBQUUsQ0FBQyxDQUFDLFVBQVUsQUFDN0IsQ0FBQyxBQUVELG9CQUFNLENBQUMsRUFBRSxjQUFDLENBQUMsQUFDVCxXQUFXLENBQUUsQ0FBQyxDQUNkLFNBQVMsQ0FBRSxJQUFJLENBQUMsVUFBVSxBQUM1QixDQUFDLEFBQ0QsS0FBSyw0QkFBQyxDQUFDLEFBQ0wsU0FBUyxDQUFFLElBQUksQ0FDZixjQUFjLENBQUUsSUFBSSxDQUVwQixhQUFhLENBQUUsSUFBSSxBQUNyQixDQUFDLEFBRUQsT0FBTyw0QkFBQyxDQUFDLEFBQ1AsU0FBUyxDQUFFLEtBQUssQ0FDaEIsWUFBWSxDQUFFLElBQUksQUFDcEIsQ0FBQyxBQUNILENBQUMsQUFFRCxJQUFJLDRCQUFDLENBQUMsQUFDSixTQUFTLENBQUUsSUFBSSxDQUNmLEtBQUssQ0FBRSxLQUFLLENBQUMsVUFBVSxBQUN6QixDQUFDLEFBRUQsa0JBQWtCLDRCQUFDLENBQUMsQUFDbEIsY0FBYyxDQUFFLFdBQVcsQ0FBQyxVQUFVLEFBQ3hDLENBQUMsQUFFRCxNQUFNLDRCQUFDLENBQUMsQUFDTixPQUFPLENBQUUsV0FBVyxDQUNwQixPQUFPLENBQUUsR0FBRyxDQUNaLE9BQU8sQ0FBRSxJQUFJLENBQ2IsY0FBYyxDQUFFLEtBQUssQ0FDckIsV0FBVyxDQUFFLFVBQVUsQUFDekIsQ0FBQyxBQUNELFNBQVMsNEJBQUMsQ0FBQyxBQUNULE9BQU8sQ0FBRSxJQUFJLENBQ2IsS0FBSyxDQUFFLElBQUksR0FBRyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsVUFBVSxBQUNwQyxDQUFDLEFBRUQsUUFBUSw0QkFBQyxDQUFDLEFBQ1IsS0FBSyxDQUFFLElBQUksR0FBRyxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsRUFBRSxDQUFDLENBQUMsVUFBVSxDQUNsQyxjQUFjLENBQUUsSUFBSSxBQUN0QixDQUFDLEFBQ0QsT0FBTyw0QkFBQyxDQUFDLEFBQ1AsT0FBTyxDQUFFLEdBQUcsQ0FDWixjQUFjLENBQUUsR0FBRyxBQUNyQixDQUFDLEFBRUQsSUFBSSw0QkFBQyxDQUFDLEFBQ0osS0FBSyxDQUFFLEtBQUssQ0FDWixNQUFNLENBQUUsSUFBSSxBQUNkLENBQUMifQ== */";
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(document.head, style);
}

function create_fragment(ctx) {
	let div18;
	let div4;
	let div3;
	let div2;
	let div0;
	let h10;
	let t0;
	let br;
	let t1;
	let t2;
	let div1;
	let p0;
	let t3;
	let t4;
	let span;
	let i;
	let t5;
	let div12;
	let div6;
	let div5;
	let h11;
	let t6;
	let t7;
	let div11;
	let div10;
	let img;
	let img_src_value;
	let t8;
	let div9;
	let div8;
	let div7;
	let h50;
	let t9;
	let t10;
	let p1;
	let t11;
	let t12;
	let div17;
	let hr0;
	let t13;
	let div13;
	let h12;
	let t14;
	let t15;
	let div14;
	let h51;
	let t16;
	let t17;
	let button;
	let a;
	let t18;
	let t19;
	let div15;
	let iframe;
	let iframe_src_value;
	let t20;
	let div16;
	let hr1;

	const block = {
		c: function create() {
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("¿Qué es\n            ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("br");
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("\n            Zarigüeya?");
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Un espacio destinado a las familias donde podrán asesorarse en\n            porteo ergonomico, conocer diferentes modelos de portabebés y\n            adquirir el que se adapte a sus necesidades. Promueve el porteo y la\n            crianza respetuosa a traves de asesoramientos grupales, rondas,\n            talleres y clases de bailes porteando.");
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("span");
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("i");
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nosotras");
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("img");
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Estefi");
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("p");
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Organizadora de eventos/ Doula / Consultora en porteo de Crianza\n                en Brazos.");
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h1");
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Nuestro Espacio");
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("h5");
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactamos tu visita con previo aviso");
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("button");
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("a");
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["text"])("Pactar visita");
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("iframe");
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["space"])();
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("hr");
			this.h();
		},
		l: function claim(nodes) {
			div18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true });
			var div18_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div18);
			div4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "DIV", { class: true });
			var div4_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div4);
			div3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div4_nodes, "DIV", { class: true });
			var div3_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div3);
			div2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "DIV", { class: true });
			var div2_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div2);
			div0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div0);
			h10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div0_nodes, "H1", { class: true });
			var h10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h10);
			t0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "¿Qué es\n            ");
			br = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(h10_nodes, "BR", {});
			t1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h10_nodes, "\n            Zarigüeya?");
			h10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t2 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div2_nodes);
			div1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div2_nodes, "DIV", { class: true });
			var div1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div1);
			p0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div1_nodes, "P", { class: true });
			var p0_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p0);
			t3 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p0_nodes, "Un espacio destinado a las familias donde podrán asesorarse en\n            porteo ergonomico, conocer diferentes modelos de portabebés y\n            adquirir el que se adapte a sus necesidades. Promueve el porteo y la\n            crianza respetuosa a traves de asesoramientos grupales, rondas,\n            talleres y clases de bailes porteando.");
			p0_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div2_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t4 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div3_nodes);
			span = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div3_nodes, "SPAN", { class: true });
			var span_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(span);
			i = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(span_nodes, "I", { class: true });
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(i).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			span_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div3_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div4_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div18_nodes);
			div12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "DIV", { class: true });
			var div12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div12);
			div6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "DIV", { class: true });
			var div6_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div6);
			div5 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div6_nodes, "DIV", { class: true });
			var div5_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div5);
			h11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div5_nodes, "H1", { class: true });
			var h11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h11);
			t6 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h11_nodes, "Nosotras");
			h11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div5_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div6_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div12_nodes);
			div11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div12_nodes, "DIV", { class: true });
			var div11_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div11);
			div10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div11_nodes, "DIV", { class: true });
			var div10_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div10);
			img = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "IMG", { alt: true, class: true, src: true });
			t8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div10_nodes);
			div9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div10_nodes, "DIV", { class: true });
			var div9_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div9);
			div8 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div9_nodes, "DIV", { class: true });
			var div8_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div8);
			div7 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div8_nodes, "DIV", { class: true });
			var div7_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div7);
			h50 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "H5", { class: true });
			var h50_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h50);
			t9 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h50_nodes, "Estefi");
			h50_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t10 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div7_nodes);
			p1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div7_nodes, "P", {});
			var p1_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(p1);
			t11 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(p1_nodes, "Organizadora de eventos/ Doula / Consultora en porteo de Crianza\n                en Brazos.");
			p1_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div7_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div8_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div9_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div10_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div11_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div18_nodes);
			div17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div18_nodes, "DIV", { class: true });
			var div17_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div17);
			hr0 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "HR", {});
			t13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div13 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div13_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div13);
			h12 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div13_nodes, "H1", {});
			var h12_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h12);
			t14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h12_nodes, "Nuestro Espacio");
			h12_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div13_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div14 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div14_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div14);
			h51 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div14_nodes, "H5", {});
			var h51_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(h51);
			t16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(h51_nodes, "Pactamos tu visita con previo aviso");
			h51_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div14_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t17 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			button = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "BUTTON", { type: true, class: true });
			var button_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(button);
			a = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(button_nodes, "A", { target: true, href: true, class: true });
			var a_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(a);
			t18 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_text"])(a_nodes, "Pactar visita");
			a_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			button_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t19 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div15 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div15_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div15);

			iframe = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div15_nodes, "IFRAME", {
				title: true,
				allowFullScreen: true,
				class: true,
				frameBorder: true,
				height: true,
				src: true,
				styles: true,
				width: true
			});

			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(iframe).forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div15_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			t20 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_space"])(div17_nodes);
			div16 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div17_nodes, "DIV", { class: true });
			var div16_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div16);
			hr1 = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(div16_nodes, "HR", {});
			div16_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div17_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			div18_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(br, file, 160, 12, 2983);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h10, "class", " text-center svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h10, file, 158, 10, 2925);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div0, "class", "col-12 col-md-6 title pt-xs-10 svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div0, file, 157, 8, 2870);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(p0, "class", "lead text-center desc svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p0, file, 165, 10, 3092);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div1, "class", "col-12 col-md-6");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div1, file, 164, 8, 3052);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div2, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div2, file, 156, 6, 2844);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(i, "class", "fas fa-angle-double-down align-text-bottom svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(i, file, 177, 8, 3626);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(span, "class", "arrow bounce align-text-bottom d-none d-md-inline text-center svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(span, file, 175, 6, 3533);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div3, "class", "banner");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div3, file, 155, 4, 2817);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div4, "class", "jumbotron svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div4, file, 154, 2, 2789);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h11, "class", "nosotras-title svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h11, file, 184, 8, 3809);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div5, "class", "col");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div5, file, 183, 6, 3783);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div6, "class", "row text-center");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div6, file, 182, 4, 3747);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "alt", "...");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "class", "align-self-center mr-3 aleimg svelte-sb05x7");
			if (img.src !== (img_src_value = /*estefi*/ ctx[0])) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(img, "src", img_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(img, file, 189, 8, 3980);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(h50, "class", "mt-0 mb-1");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h50, file, 193, 14, 4163);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(p1, file, 194, 14, 4211);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div7, "class", "media-body");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div7, file, 192, 12, 4124);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div8, "class", "col-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div8, file, 191, 10, 4091);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div9, "class", "media row svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div9, file, 190, 8, 4057);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div10, "class", "col-12 col-md-12");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div10, file, 188, 6, 3941);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div11, "class", "row nosotras text-center align-self-center svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div11, file, 187, 4, 3878);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div12, "class", "container");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div12, file, 181, 2, 3719);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr0, file, 206, 4, 4465);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h12, file, 208, 6, 4500);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div13, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div13, file, 207, 4, 4476);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(h51, file, 211, 6, 4571);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div14, "class", "row visita svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div14, file, 210, 4, 4540);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "target", "_blank");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "href", "https://api.whatsapp.com/send?phone=5493624260839&text=Me%20interesa%20pactar%20una%20cita");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(a, "class", "svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(a, file, 215, 6, 4684);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "type", "button");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(button, "class", "btn btn-danger svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(button, file, 214, 4, 4632);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "title", "mapa");
			iframe.allowFullscreen = "";
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "class", "map svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "frameborder", "0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "height", "600");
			if (iframe.src !== (iframe_src_value = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3540.470949803796!2d-59.00476088484895!3d-27.454593982897237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x94450c86474e0c27%3A0x66a2b9bcf6bff521!2sCangallo+1137%2C+H3508+Resistencia%2C+Chaco!5e0!3m2!1ses-419!2sar!4v1556198319410!5m2!1ses-419!2sar")) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "src", iframe_src_value);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "styles", "border:0");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(iframe, "width", "800");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(iframe, file, 223, 6, 4894);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div15, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div15, file, 222, 4, 4870);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(hr1, file, 234, 6, 5424);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div16, "class", "row");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div16, file, 233, 4, 5400);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div17, "class", "container espacio svelte-sb05x7");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div17, file, 205, 2, 4429);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div18, "class", "fullcontainer");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div18, file, 153, 0, 2759);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div18, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, div4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div4, div3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, div2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div0, h10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, br);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h10, t1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, t2);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div2, div1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div1, p0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p0, t3);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, t4);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div3, span);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(span, i);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, t5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, div12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, div6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div6, div5);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div5, h11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h11, t6);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, t7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div12, div11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div11, div10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, img);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, t8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div10, div9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div9, div8);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div8, div7);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, h50);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h50, t9);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, t10);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div7, p1);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(p1, t11);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, t12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div18, div17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, hr0);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div13);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div13, h12);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h12, t14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div14);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div14, h51);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(h51, t16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t17);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, button);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(button, a);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(a, t18);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t19);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div15);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div15, iframe);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, t20);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div17, div16);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["append_dev"])(div16, hr1);
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		o: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div18);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let ale = "assets/Images/about/ale.png";
	let estefi = "assets/Images/about/estefi.png";
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<AboutComponent> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("AboutComponent", $$slots, []);
	$$self.$capture_state = () => ({ ale, estefi });

	$$self.$inject_state = $$props => {
		if ("ale" in $$props) ale = $$props.ale;
		if ("estefi" in $$props) $$invalidate(0, estefi = $$props.estefi);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [estefi];
}

class AboutComponent extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		if (!document.getElementById("svelte-sb05x7-style")) add_css();
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "AboutComponent",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (AboutComponent);


/***/ }),

/***/ "./src/routes/about.svelte":
/*!*********************************!*\
  !*** ./src/routes/about.svelte ***!
  \*********************************/
/*! exports provided: default */
/***/ (function(module, __webpack_exports__, __webpack_require__) {

"use strict";
__webpack_require__.r(__webpack_exports__);
/* harmony import */ var svelte_internal__WEBPACK_IMPORTED_MODULE_0__ = __webpack_require__(/*! svelte/internal */ "./node_modules/svelte/internal/index.mjs");
/* harmony import */ var _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__ = __webpack_require__(/*! ../components/AboutComponent.svelte */ "./src/components/AboutComponent.svelte");
/* src/routes/about.svelte generated by Svelte v3.24.0 */



const file = "src/routes/about.svelte";

function create_fragment(ctx) {
	let div;
	let aboutcomponent;
	let current;
	aboutcomponent = new _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"]({ $$inline: true });

	const block = {
		c: function create() {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["element"])("div");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["create_component"])(aboutcomponent.$$.fragment);
			this.h();
		},
		l: function claim(nodes) {
			div = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_element"])(nodes, "DIV", { class: true, id: true });
			var div_nodes = Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["children"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["claim_component"])(aboutcomponent.$$.fragment, div_nodes);
			div_nodes.forEach(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"]);
			this.h();
		},
		h: function hydrate() {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "class", "containerfluid");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["attr_dev"])(div, "id", "about");
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["add_location"])(div, file, 4, 0, 90);
		},
		m: function mount(target, anchor) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["insert_dev"])(target, div, anchor);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["mount_component"])(aboutcomponent, div, null);
			current = true;
		},
		p: svelte_internal__WEBPACK_IMPORTED_MODULE_0__["noop"],
		i: function intro(local) {
			if (current) return;
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_in"])(aboutcomponent.$$.fragment, local);
			current = true;
		},
		o: function outro(local) {
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["transition_out"])(aboutcomponent.$$.fragment, local);
			current = false;
		},
		d: function destroy(detaching) {
			if (detaching) Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["detach_dev"])(div);
			Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["destroy_component"])(aboutcomponent);
		}
	};

	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== "$$") console.warn(`<About> was created with unknown prop '${key}'`);
	});

	let { $$slots = {}, $$scope } = $$props;
	Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["validate_slots"])("About", $$slots, []);
	$$self.$capture_state = () => ({ AboutComponent: _components_AboutComponent_svelte__WEBPACK_IMPORTED_MODULE_1__["default"] });
	return [];
}

class About extends svelte_internal__WEBPACK_IMPORTED_MODULE_0__["SvelteComponentDev"] {
	constructor(options) {
		super(options);
		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["init"])(this, options, instance, create_fragment, svelte_internal__WEBPACK_IMPORTED_MODULE_0__["safe_not_equal"], {});

		Object(svelte_internal__WEBPACK_IMPORTED_MODULE_0__["dispatch_dev"])("SvelteRegisterComponent", {
			component: this,
			tagName: "About",
			options,
			id: create_fragment.name
		});
	}
}


if (false) {}

/* harmony default export */ __webpack_exports__["default"] = (About);


/***/ })

}]);
//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIndlYnBhY2s6Ly8vLi9zcmMvY29tcG9uZW50cy9BYm91dENvbXBvbmVudC5zdmVsdGUiLCJ3ZWJwYWNrOi8vLy4vc3JjL3JvdXRlcy9hYm91dC5zdmVsdGUiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6Ijs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7K0NBNkxrRSxHQUFNOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztLQTVMbEUsR0FBRyxHQUFHLDZCQUE2QjtLQUNuQyxNQUFNLEdBQUcsZ0NBQWdDOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUNEc0IiLCJmaWxlIjoiMDYwOWE2YWRmNjg3ZmUwODhlNTgvYWJvdXQuYWJvdXQuanMiLCJzb3VyY2VzQ29udGVudCI6WyI8c2NyaXB0PlxuICBsZXQgYWxlID0gXCJhc3NldHMvSW1hZ2VzL2Fib3V0L2FsZS5wbmdcIjtcbiAgbGV0IGVzdGVmaSA9IFwiYXNzZXRzL0ltYWdlcy9hYm91dC9lc3RlZmkucG5nXCI7XG48L3NjcmlwdD5cblxuPHN0eWxlPlxuICAuYnRuLWRhbmdlciB7XG4gICAgbWFyZ2luLWJvdHRvbTogMTBweDtcbiAgfVxuICBhIHtcbiAgICB0ZXh0LWRlY29yYXRpb246IGluaGVyaXQ7XG4gICAgY29sb3I6IGluaGVyaXQ7XG4gICAgY3Vyc29yOiBwb2ludGVyO1xuICB9XG4gIC5ib3VuY2Uge1xuICAgIGFuaW1hdGlvbjogYm91bmNlIDJzIGluZmluaXRlO1xuICB9XG5cbiAgQGtleWZyYW1lcyBib3VuY2Uge1xuICAgIDAlLFxuICAgIDIwJSxcbiAgICA1MCUsXG4gICAgODAlLFxuICAgIDEwMCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKDApO1xuICAgIH1cbiAgICA0MCUge1xuICAgICAgdHJhbnNmb3JtOiB0cmFuc2xhdGVZKC0zMHB4KTtcbiAgICB9XG4gICAgNjAlIHtcbiAgICAgIHRyYW5zZm9ybTogdHJhbnNsYXRlWSgtMTVweCk7XG4gICAgfVxuICB9XG5cbiAgLmZhLWFuZ2xlLWRvdWJsZS1kb3duIHtcbiAgICBmb250LXNpemU6IDcwcHggIWltcG9ydGFudDtcbiAgfVxuICBAbWVkaWEgKG1pbi13aWR0aDogNzY4cHgpIHtcbiAgICAuanVtYm90cm9uIHtcbiAgICAgIGJhY2tncm91bmQtaW1hZ2U6IHVybChcImFzc2V0cy9JbWFnZXMvYWJvdXQvZXNwLmpwZ1wiKTtcbiAgICAgIGJhY2tncm91bmQtc2l6ZTogY292ZXI7XG4gICAgICBiYWNrZ3JvdW5kLXJlcGVhdDogbm8tcmVwZWF0O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgaGVpZ2h0OiA5MHZoO1xuICAgICAgbWFyZ2luOiAwICFpbXBvcnRhbnQ7XG4gICAgICBvdmVyZmxvdzogaGlkZGVuO1xuICAgICAgcGFkZGluZy10b3A6IDE1cHggIWltcG9ydGFudDtcbiAgICAgIHBhZGRpbmctYm90dG9tOiAwICFpbXBvcnRhbnQ7XG4gICAgICBib3JkZXItcmFkaXVzOiAwICFpbXBvcnRhbnQ7XG4gICAgfVxuICAgIC5hcnJvdyB7XG4gICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgICBtYXJnaW46IDglIDA7XG4gICAgICBwb3NpdGlvbjogYWJzb2x1dGU7XG4gICAgICB0b3A6IDgwdmg7XG4gICAgICBsZWZ0OiA0OHZ3O1xuICAgICAgY29sb3I6IHdoaXRlO1xuICAgICAgcGFkZGluZzogMDtcbiAgICAgIG1hcmdpbjogMDtcbiAgICAgIHotaW5kZXg6IDQ7XG4gICAgICBkaXNwbGF5OiBpbmxpbmU7XG4gICAgICB0ZXh0LWFsaWduOiBjZW50ZXI7XG4gICAgICBvcGFjaXR5OiAwLjY7XG4gICAgfVxuXG4gICAgLnRpdGxlIGgxIHtcbiAgICAgIHBhZGRpbmctdG9wOiAyOXZoO1xuICAgICAgZm9udC1zaXplOiA1LjVyZW07XG4gICAgfVxuICAgIC5sZWFkIHtcbiAgICAgIGZvbnQtc2l6ZTogMS43dnc7XG4gICAgICBwYWRkaW5nLWJvdHRvbTogMjBweDtcbiAgICAgIHBhZGRpbmctdG9wOiAzMHZoO1xuICAgIH1cblxuICAgIC5hbGVpbWcge1xuICAgICAgbWF4LXdpZHRoOiAxMnZ3O1xuICAgICAgcGFkZGluZy1sZWZ0OiAyMHB4O1xuICAgIH1cbiAgfVxuXG4gIC5ub3NvdHJhcy10aXRsZSB7XG4gICAgcGFkZGluZzogMTVweDtcbiAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICB9XG5cbiAgQG1lZGlhIChtYXgtd2lkdGg6IDc2OHB4KSB7XG4gICAgLmp1bWJvdHJvbiB7XG4gICAgICBiYWNrZ3JvdW5kLWltYWdlOiB1cmwoXCJhc3NldHMvSW1hZ2VzL2Fib3V0L2VzcGFjaW8uanBnXCIpO1xuICAgICAgYmFja2dyb3VuZC1zaXplOiBjb3ZlcjtcbiAgICAgIGJhY2tncm91bmQtcmVwZWF0OiBuby1yZXBlYXQ7XG4gICAgICBjb2xvcjogd2hpdGU7XG4gICAgICBoZWlnaHQ6IDE4MHZ3O1xuICAgICAgbWFyZ2luOiAwICFpbXBvcnRhbnQ7XG4gICAgICBvdmVyZmxvdzogaGlkZGVuO1xuICAgICAgcGFkZGluZy10b3A6IDE1cHggIWltcG9ydGFudDtcbiAgICAgIHBhZGRpbmctYm90dG9tOiAwICFpbXBvcnRhbnQ7XG4gICAgICBib3JkZXItcmFkaXVzOiAwICFpbXBvcnRhbnQ7XG4gICAgfVxuXG4gICAgLnRpdGxlIGgxIHtcbiAgICAgIHBhZGRpbmctdG9wOiAwO1xuICAgICAgZm9udC1zaXplOiA2MHB4ICFpbXBvcnRhbnQ7XG4gICAgfVxuICAgIC5sZWFkIHtcbiAgICAgIGZvbnQtc2l6ZTogMThweDtcbiAgICAgIHBhZGRpbmctYm90dG9tOiAyMHB4O1xuICAgICAgLyogcGFkZGluZy10b3A6IDsgKi9cbiAgICAgIG1hcmdpbi1ib3R0b206IDI1cHg7XG4gICAgfVxuXG4gICAgLmFsZWltZyB7XG4gICAgICBtYXgtd2lkdGg6IDEwMHB4O1xuICAgICAgcGFkZGluZy1sZWZ0OiAyMHB4O1xuICAgIH1cbiAgfVxuXG4gIC5mYXMge1xuICAgIGZvbnQtc2l6ZTogNzBweDtcbiAgICBjb2xvcjogd2hpdGUgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5hbGlnbi10ZXh0LWJvdHRvbSB7XG4gICAgdmVydGljYWwtYWxpZ246IHRleHQtYm90dG9tICFpbXBvcnRhbnQ7XG4gIH1cblxuICAubWVkaWEge1xuICAgIGRpc3BsYXk6IC1tcy1mbGV4Ym94O1xuICAgIHBhZGRpbmc6IDVweDtcbiAgICBkaXNwbGF5OiBmbGV4O1xuICAgIC1tcy1mbGV4LWFsaWduOiBzdGFydDtcbiAgICBhbGlnbi1pdGVtczogZmxleC1zdGFydDtcbiAgfVxuICAubm9zb3RyYXMge1xuICAgIHBhZGRpbmc6IDE1cHg7XG4gICAgY29sb3I6IHJnYigxOTAsIDg2LCA4OSkgIWltcG9ydGFudDtcbiAgfVxuXG4gIC5lc3BhY2lvIHtcbiAgICBjb2xvcjogcmdiKDE5MCwgODYsIDg5KSAhaW1wb3J0YW50O1xuICAgIHBhZGRpbmctYm90dG9tOiAxNXB4O1xuICB9XG4gIC52aXNpdGEge1xuICAgIG9wYWNpdHk6IDAuNTtcbiAgICBwYWRkaW5nLWJvdHRvbTogM3B4O1xuICB9XG5cbiAgLm1hcCB7XG4gICAgd2lkdGg6IDEwMHZ3O1xuICAgIGhlaWdodDogNDB2aDtcbiAgfVxuPC9zdHlsZT5cblxuPGRpdiBjbGFzcz1cImZ1bGxjb250YWluZXJcIj5cbiAgPGRpdiBjbGFzcz1cImp1bWJvdHJvblwiPlxuICAgIDxkaXYgY2xhc3M9XCJiYW5uZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMiBjb2wtbWQtNiB0aXRsZSBwdC14cy0xMFwiPlxuICAgICAgICAgIDxoMSBjbGFzcz1cIiB0ZXh0LWNlbnRlclwiPlxuICAgICAgICAgICAgwr9RdcOpIGVzXG4gICAgICAgICAgICA8YnIgLz5cbiAgICAgICAgICAgIFphcmlnw7xleWE/XG4gICAgICAgICAgPC9oMT5cbiAgICAgICAgPC9kaXY+XG4gICAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTZcIj5cbiAgICAgICAgICA8cCBjbGFzcz1cImxlYWQgdGV4dC1jZW50ZXIgZGVzY1wiPlxuICAgICAgICAgICAgVW4gZXNwYWNpbyBkZXN0aW5hZG8gYSBsYXMgZmFtaWxpYXMgZG9uZGUgcG9kcsOhbiBhc2Vzb3JhcnNlIGVuXG4gICAgICAgICAgICBwb3J0ZW8gZXJnb25vbWljbywgY29ub2NlciBkaWZlcmVudGVzIG1vZGVsb3MgZGUgcG9ydGFiZWLDqXMgeVxuICAgICAgICAgICAgYWRxdWlyaXIgZWwgcXVlIHNlIGFkYXB0ZSBhIHN1cyBuZWNlc2lkYWRlcy4gUHJvbXVldmUgZWwgcG9ydGVvIHkgbGFcbiAgICAgICAgICAgIGNyaWFuemEgcmVzcGV0dW9zYSBhIHRyYXZlcyBkZSBhc2Vzb3JhbWllbnRvcyBncnVwYWxlcywgcm9uZGFzLFxuICAgICAgICAgICAgdGFsbGVyZXMgeSBjbGFzZXMgZGUgYmFpbGVzIHBvcnRlYW5kby5cbiAgICAgICAgICA8L3A+XG4gICAgICAgIDwvZGl2PlxuXG4gICAgICA8L2Rpdj5cbiAgICAgIDxzcGFuXG4gICAgICAgIGNsYXNzPVwiYXJyb3cgYm91bmNlIGFsaWduLXRleHQtYm90dG9tIGQtbm9uZSBkLW1kLWlubGluZSB0ZXh0LWNlbnRlclwiPlxuICAgICAgICA8aSBjbGFzcz1cImZhcyBmYS1hbmdsZS1kb3VibGUtZG93biBhbGlnbi10ZXh0LWJvdHRvbVwiIC8+XG4gICAgICA8L3NwYW4+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuICA8ZGl2IGNsYXNzPVwiY29udGFpbmVyXCI+XG4gICAgPGRpdiBjbGFzcz1cInJvdyB0ZXh0LWNlbnRlclwiPlxuICAgICAgPGRpdiBjbGFzcz1cImNvbFwiPlxuICAgICAgICA8aDEgY2xhc3M9XCJub3NvdHJhcy10aXRsZVwiPk5vc290cmFzPC9oMT5cbiAgICAgIDwvZGl2PlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgbm9zb3RyYXMgdGV4dC1jZW50ZXIgYWxpZ24tc2VsZi1jZW50ZXJcIj5cbiAgICAgIDxkaXYgY2xhc3M9XCJjb2wtMTIgY29sLW1kLTEyXCI+XG4gICAgICAgIDxpbWcgYWx0PVwiLi4uXCIgY2xhc3M9XCJhbGlnbi1zZWxmLWNlbnRlciBtci0zIGFsZWltZ1wiIHNyYz17ZXN0ZWZpfSAvPlxuICAgICAgICA8ZGl2IGNsYXNzPVwibWVkaWEgcm93XCI+XG4gICAgICAgICAgPGRpdiBjbGFzcz1cImNvbC0xMlwiPlxuICAgICAgICAgICAgPGRpdiBjbGFzcz1cIm1lZGlhLWJvZHlcIj5cbiAgICAgICAgICAgICAgPGg1IGNsYXNzPVwibXQtMCBtYi0xXCI+RXN0ZWZpPC9oNT5cbiAgICAgICAgICAgICAgPHA+XG4gICAgICAgICAgICAgICAgT3JnYW5pemFkb3JhIGRlIGV2ZW50b3MvIERvdWxhIC8gQ29uc3VsdG9yYSBlbiBwb3J0ZW8gZGUgQ3JpYW56YVxuICAgICAgICAgICAgICAgIGVuIEJyYXpvcy5cbiAgICAgICAgICAgICAgPC9wPlxuICAgICAgICAgICAgPC9kaXY+XG4gICAgICAgICAgPC9kaXY+XG4gICAgICAgIDwvZGl2PlxuICAgICAgPC9kaXY+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuXG4gIDxkaXYgY2xhc3M9XCJjb250YWluZXIgZXNwYWNpb1wiPlxuICAgIDxociAvPlxuICAgIDxkaXYgY2xhc3M9XCJyb3dcIj5cbiAgICAgIDxoMT5OdWVzdHJvIEVzcGFjaW88L2gxPlxuICAgIDwvZGl2PlxuICAgIDxkaXYgY2xhc3M9XCJyb3cgdmlzaXRhXCI+XG4gICAgICA8aDU+UGFjdGFtb3MgdHUgdmlzaXRhIGNvbiBwcmV2aW8gYXZpc288L2g1PlxuXG4gICAgPC9kaXY+XG4gICAgPGJ1dHRvbiB0eXBlPVwiYnV0dG9uXCIgY2xhc3M9XCJidG4gYnRuLWRhbmdlclwiPlxuICAgICAgPGFcbiAgICAgICAgdGFyZ2V0PVwiX2JsYW5rXCJcbiAgICAgICAgaHJlZj1cImh0dHBzOi8vYXBpLndoYXRzYXBwLmNvbS9zZW5kP3Bob25lPTU0OTM2MjQyNjA4MzkmdGV4dD1NZSUyMGludGVyZXNhJTIwcGFjdGFyJTIwdW5hJTIwY2l0YVwiPlxuICAgICAgICBQYWN0YXIgdmlzaXRhXG4gICAgICA8L2E+XG4gICAgPC9idXR0b24+XG5cbiAgICA8ZGl2IGNsYXNzPVwicm93XCI+XG4gICAgICA8aWZyYW1lXG4gICAgICAgIHRpdGxlPVwibWFwYVwiXG4gICAgICAgIGFsbG93RnVsbFNjcmVlbj1cIlwiXG4gICAgICAgIGNsYXNzPVwibWFwXCJcbiAgICAgICAgZnJhbWVCb3JkZXI9XCIwXCJcbiAgICAgICAgaGVpZ2h0PVwiNjAwXCJcbiAgICAgICAgc3JjPVwiaHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS9tYXBzL2VtYmVkP3BiPSExbTE4ITFtMTIhMW0zITFkMzU0MC40NzA5NDk4MDM3OTYhMmQtNTkuMDA0NzYwODg0ODQ4OTUhM2QtMjcuNDU0NTkzOTgyODk3MjM3ITJtMyExZjAhMmYwITNmMCEzbTIhMWkxMDI0ITJpNzY4ITRmMTMuMSEzbTMhMW0yITFzMHg5NDQ1MGM4NjQ3NGUwYzI3JTNBMHg2NmEyYjliY2Y2YmZmNTIxITJzQ2FuZ2FsbG8rMTEzNyUyQytIMzUwOCtSZXNpc3RlbmNpYSUyQytDaGFjbyE1ZTAhM20yITFzZXMtNDE5ITJzYXIhNHYxNTU2MTk4MzE5NDEwITVtMiExc2VzLTQxOSEyc2FyXCJcbiAgICAgICAgc3R5bGVzPVwiYm9yZGVyOjBcIlxuICAgICAgICB3aWR0aD1cIjgwMFwiIC8+XG4gICAgPC9kaXY+XG4gICAgPGRpdiBjbGFzcz1cInJvd1wiPlxuICAgICAgPGhyIC8+XG4gICAgPC9kaXY+XG4gIDwvZGl2PlxuPC9kaXY+XG4iLCI8c2NyaXB0PlxuICAgIGltcG9ydCBBYm91dENvbXBvbmVudCBmcm9tICcuLi9jb21wb25lbnRzL0Fib3V0Q29tcG9uZW50LnN2ZWx0ZSc7XG48L3NjcmlwdD5cblxuPGRpdiBjbGFzcz1cImNvbnRhaW5lcmZsdWlkXCIgaWQ9XCJhYm91dFwiPlxuICAgIDxBYm91dENvbXBvbmVudCAvPlxuPC9kaXY+XG5cbjxzdHlsZT5cblxuPC9zdHlsZT5cbiJdLCJzb3VyY2VSb290IjoiIn0=